### ISSUE TITLE
[DeepLink][Web]Incorrect behavior when use browser's back button

### ISSUE THREAD

**Issue by qcnguyen** [ionic-team/ionic#11469]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
first, at root page "RootPageA" , user navigate to another root page "RootPageB" (using Nav.SetRoot method), then he press browser's back button to go back to the previous root page (RootPageA ). But now, the screen is displayed as it was a pushed page, not a root page (judged by the back button is shown, instead of menu button). Please see this screenshot:
![backbug](https://cloud.githubusercontent.com/assets/11658651/25630682/889661bc-2fa0-11e7-9737-dd57d7c50fdd.gif)

**Expected behavior:**
Show menu button.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Could you post a minimal repo we could use to reproduce this issue?

**Comment by qcnguyen** [comment]
hi jgw96,
this is my repo, please help me, Thank you very much.

https://drive.google.com/open?id=0Bwrl__NBSvoSdURJRW9heWxzeVE

**Comment by yozman** [comment]
@danbucholtz 
would u please look into this bug?
it's still on the newest release

**Comment by emin93** [comment]
I investigated the issue and found a workaround. It seems that the segment has the wrong id when using the browser navigation. It's in the `_loadViewForSegment` helper method where it decides if it should push or pop after the browser url change. Instead of comparing id's i use their names since they seem to be correct.

So instead of:
`if (viewController && viewController.id === segment.id) {`
i now use:
`if (viewController && viewController.name === segment.name) {`

I created a fork with the commit which fixes it and it's working for my case, but i'm not sure if this causes any other issues.

**Comment by danbucholtz** [comment]
I believe this is fixed with the most recent nav changes. Please let me know if you have issues with `ionic-angular` `3.5.0` which ships tomorrow.

Thanks,
Dan

**Comment by yozman** [comment]
@danbucholtz 
OK, I'll check it

**Comment by emin93** [comment]
I also experienced, that my workaround does not work when AOT transpiled. Hope this gets fixed with `3.5.0`.

**Comment by shawnlan** [comment]
@danbucholtz Tested with `3.5.0`. I can see that the urls now look different. However, the issues persist. For example, using Tabs template, if I go to another tab, push some pages within that tab, click browser's back button, sometimes it jumps back to the previous tab. Other times it pushes the previous tab's root page to the current tab.

This is the result of a quick test. The navigation with browser's back button is still unnatural and buggy.

Also, the ionic team closed several issues as duplicates of this issue. I think although they are all related, each one describes different scenarios. They may be worth to look at or to re-open as this issue is quite complicated. Thanks!

**Comment by danbucholtz** [comment]
@shawnlan,

The behavior that we currently have is the behavior we want. Perhaps we'll reconsider in the future.

Thanks,
Dan

**Comment by shawnlan** [comment]
@danbucholtz Sometimes the recreated page doesn't not get `navParams`. https://github.com/ionic-team/ionic/issues/11698

I have set `rootParams` for some tabs. Now each `livereload` just breaks the page because of this issue.

**Comment by viveksinha9** [comment]
@shawnlan I am also facing this issue. Have you solved it?

**Comment by rodanato** [comment]
I have this issue and I'm working with "ionic-angular": "3.9.2"
