### ISSUE TITLE
node-sass version error

### ISSUE THREAD

**Issue by vitoriaserra** [ionic-team/ionic#11913]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Error using the "ionic start ..." command
He is looking for the wrong version...

**Expected behavior:**
The correct path would be: 
[https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-57_binding.node](url)

**Steps to reproduce:**
![error](https://cloud.githubusercontent.com/assets/7915437/26759366/15642774-48d2-11e7-849c-20c38a7ff938.PNG)

**Related code:**

```
c:\Users\Developer-PC\Documents>ionic start myApp blank
✔ Creating directory .\myApp - done!
[INFO] Fetching app base (https://github.com/ionic-team/ionic2-app-base/archive/master.tar.gz)
✔ Downloading - done!
[INFO] Fetching starter template blank (https://github.com/ionic-team/ionic2-starter-blank/archive/master.tar.gz)
✔ Downloading - done!
✔ Updating package.json with app details - done!
✔ Creating configuration file ionic.config.json - done!
[INFO] Installing dependencies may take several minutes!
> npm install
✖ Running command - failed!
[ERROR] An error occurred while running npm install (exit code 1):

        npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
        npm WARN prefer global node-gyp@3.6.2 should be installed with -g

        > node-sass@4.5.0 install c:\Users\Developer-PC\Documents\myApp\node_modules\node-sass
        > node scripts/install.js

        Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-57_binding.node
        Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-57_binding.node":

        HTTP error 404 Not Found

        Hint: If github.com is not accessible in your location
              try setting a proxy via HTTP_PROXY, e.g.

              export HTTP_PROXY=http://example.com:1234

        or configure npm proxy via

              npm config set proxy http://example.com:8080

        > fsevents@1.1.1 install c:\Users\Developer-PC\Documents\myApp\node_modules\fsevents
        > node install


        > node-sass@4.5.0 postinstall c:\Users\Developer-PC\Documents\myApp\node_modules\node-sass
        > node scripts/build.js

        Building: C:\Users\Developer-PC\Documents\node\node.exe c:\Users\Developer-PC\Documents\myApp\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
        gyp info it worked if it ends with ok
        gyp verb cli [ 'C:\\Users\\Developer-PC\\Documents\\node\\node.exe',
        gyp verb cli   'c:\\Users\\Developer-PC\\Documents\\myApp\\node_modules\\node-gyp\\bin\\node-gyp.js',
        gyp verb cli   'rebuild',
        gyp verb cli   '--verbose',
        gyp verb cli   '--libsass_ext=',
        gyp verb cli   '--libsass_cflags=',
        gyp verb cli   '--libsass_ldflags=',
        gyp verb cli   '--libsass_library=' ]
        gyp info using node-gyp@3.6.2
        gyp info using node@8.0.0 | win32 | x64
        gyp verb command rebuild []
        gyp verb command clean []
        gyp verb clean removing "build" directory
        gyp verb command configure []
        gyp verb check python checking for Python executable "python2" in the PATH
        gyp verb `which` failed Error: not found: python2
        gyp verb `which` failed     at getNotFoundError (c:\Users\Developer-PC\Documents\myApp\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (c:\Users\Developer-PC\Documents\myApp\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (c:\Users\Developer-PC\Documents\myApp\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at c:\Users\Developer-PC\Documents\myApp\node_modules\which\which.js:89:16
        gyp verb `which` failed     at c:\Users\Developer-PC\Documents\myApp\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at c:\Users\Developer-PC\Documents\myApp\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
        gyp verb `which` failed  python2 { Error: not found: python2
        gyp verb `which` failed     at getNotFoundError (c:\Users\Developer-PC\Documents\myApp\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (c:\Users\Developer-PC\Documents\myApp\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (c:\Users\Developer-PC\Documents\myApp\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at c:\Users\Developer-PC\Documents\myApp\node_modules\which\which.js:89:16
        gyp verb `which` failed     at c:\Users\Developer-PC\Documents\myApp\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at c:\Users\Developer-PC\Documents\myApp\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
        gyp verb check python checking for Python executable "python" in the PATH
        gyp verb `which` failed Error: not found: python
        gyp verb `which` failed     at getNotFoundError (c:\Users\Developer-PC\Documents\myApp\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (c:\Users\Developer-PC\Documents\myApp\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (c:\Users\Developer-PC\Documents\myApp\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at c:\Users\Developer-PC\Documents\myApp\node_modules\which\which.js:89:16
        gyp verb `which` failed     at c:\Users\Developer-PC\Documents\myApp\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at c:\Users\Developer-PC\Documents\myApp\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
        gyp verb `which` failed  python { Error: not found: python
        gyp verb `which` failed     at getNotFoundError (c:\Users\Developer-PC\Documents\myApp\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (c:\Users\Developer-PC\Documents\myApp\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (c:\Users\Developer-PC\Documents\myApp\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at c:\Users\Developer-PC\Documents\myApp\node_modules\which\which.js:89:16
        gyp verb `which` failed     at c:\Users\Developer-PC\Documents\myApp\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at c:\Users\Developer-PC\Documents\myApp\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
        gyp verb could not find "python". checking python launcher
        gyp verb could not find "python". guessing location
        gyp verb ensuring that file exists: C:\Python27\python.exe
        gyp ERR! configure error
        gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
        gyp ERR! stack     at PythonFinder.failNoPython (c:\Users\Developer-PC\Documents\myApp\node_modules\node-gyp\lib\configure.js:483:19)
        gyp ERR! stack     at PythonFinder.<anonymous> (c:\Users\Developer-PC\Documents\myApp\node_modules\node-gyp\lib\configure.js:508:16)
        gyp ERR! stack     at c:\Users\Developer-PC\Documents\myApp\node_modules\graceful-fs\polyfills.js:284:29
        gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
        gyp ERR! System Windows_NT 10.0.15063
        gyp ERR! command "C:\\Users\\Developer-PC\\Documents\\node\\node.exe" "c:\\Users\\Developer-PC\\Documents\\myApp\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
        gyp ERR! cwd c:\Users\Developer-PC\Documents\myApp\node_modules\node-sass
        gyp ERR! node -v v8.0.0
        gyp ERR! node-gyp -v v3.6.2
        gyp ERR! not ok
        Build failed with error code: 1
        npm ERR! code ELIFECYCLE
        npm ERR! errno 1
        npm ERR! node-sass@4.5.0 postinstall: `node scripts/build.js`
        npm ERR! Exit status 1
        npm ERR!
        npm ERR! Failed at the node-sass@4.5.0 postinstall script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

        npm ERR! A complete log of this run can be found in:
        npm ERR!     C:\Users\Developer-PC\AppData\Roaming\npm-cache\_logs\2017-06-04T05_26_08_991Z-debug.log


```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
c:\Users\Developer-PC\Documents\ionic\myApp>ionic info
[ERROR] Error with .\node_modules\@ionic\app-scripts\package.json file: FILE_NOT_FOUND

global packages:

    @ionic/cli-utils : 1.3.0
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : not installed
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v8.0.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

```

**Comment by danielsogl** [comment]
@vitoriaserra This is a problem with ionic-app-scripts.
I already fixed that problem but we have to wait for the next release.
We will release it this week I guess.

**Comment by vitoriaserra** [comment]
Thank you! Please let us now

**Comment by jgw96** [comment]
Closing this as this PR https://github.com/ionic-team/ionic-app-scripts/pull/1012 fixed it. Thanks @danielsogl !

**Comment by mattezell** [comment]
I'm still having this issue under windows 10... Just me?

Node: 8.0.0
Cordova: 7.0.1
Ionic: 3.4.0
