### ISSUE TITLE
List are really slow to scroll on iOS / iPad 2

### ISSUE THREAD

**Issue by Bluestart83** [ionic-team/ionic#12733]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Scrolling a list is really slow (3 to 5 seconds response time of freeze), especially on iOS / iPad 2. So app is unusable on iPad 2, very slow on iOS
I can see the latency in safari with remote debugging.

**Expected behavior:**
Scrolling time normal.

**Steps to reproduce:**
Tested with a ion-list of 70 items (and also reproduced it with an ionic virtual scroll).
Tester should just create a list with around 70 items in it, with at least one text and 2 small <img> icons (20px x 20px).

**Related code:**
Git Repo:
https://github.com/Bluestart83/IonicSlowListTest
in home.html

**Other information:**
To fix the bug I only commented in main.css of ionic this CSS rule:
```
:focus,
:active {
  outline: none;
}
```
Commenting this rule fix everything without changing anything to the App UI.
On Android this code does not improve anything and change the appearances (for ion-checkbox as example).

You need to remove from the rule from ios project in "Staging/www/build/main.css"

main.css DEV:
```
:focus,
:active {
  outline: none;
}
```
main.css PROD:
```
:active,:focus{outline:0}
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.1
    ionic (Ionic CLI) : 3.9.1

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.4.0

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.1 
    ios-sim           : 5.0.12 
    Node              : v6.9.4
    npm               : 3.10.10 
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b 
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? I know you have some steps to duplicate, but having a sample app that duplicates the issue saves a lot of back and forth with "I tried your stuff and it worked fine", "no, you missed this detail here", etc.

Thanks for using Ionic!

**Comment by Bluestart83** [comment]
Hi,
Here is a sample code that reproduce the issue. (Updated my issue with info)

**Comment by kensodemann** [comment]
I took your code and applied the [WKWebView Engine](https://github.com/ionic-team/cordova-plugin-wkwebview-engine), which helps but does not completely solve the issue. I suggest using that and also implementing [Virtual Scroll](http://ionicframework.com/docs/api/components/virtual-scroll/VirtualScroll/) so you are not rendering so much data at one time.

**Comment by Bluestart83** [comment]
Hi, VirtualScroll does not solve anything, on iPad, even lowering buffer size, it can't simply render more than 10 lines! Also implemented WKWebView, it's just like giving vitamins to the CPU... but the problem is still there. Fixing the css is the only way!

**Comment by kensodemann** [comment]
The only way I can duplicate your original issue is by running the sample application on a 5th gen iPad simulator. However, removing the CSS that you suggest does not fix the issue. I think there is more going on there. We had a discussion internally and are reluctant to remove the CSS 

I was not able to duplicate the issue at all on any simulator for newer hardware, nor was I able to duplicate the issue on my iPhone 7.

I will urge that you ask about this issue on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Perhaps the collective knowledge found there has run across this and may have a viable fix.

We will keep this issue open for a while, and revisit it as time permits, but thus far have been only marginally able to duplicate the error, and have not been able to duplicate the fix via the CSS mod so we believe there is more going on.

Thanks for using Ionic!

**Comment by Bluestart83** [comment]
If you use a real device (having the same CPU performance), you will observe that the framework is unusable on such device without doing this change on iOS. My client could tell it to you...

**Comment by mochtu** [comment]
+1
The issue happens on older iPads (iPad Mini 2@iOS10, iPad 2@iOS9) but does not appear in the simulator. We couldn't believe it at first, but the CSS fix mentioned above works. I think this issue should be seriously addressed because it is very hard to figure for developers and the fix is very 'strange'. 

From this personal experience I can only urge you to test on native devices as much as possible.

Thanks for making ionic awesome! Cheers!

**Comment by kensodemann** [comment]
I have been documenting some issues that need to be tested after Ionic v4 is released to determine if they are fixed or still need attention (v4 has a fair amount of CSS mods as well as the general performance gains we are looking to get out of using Stencil). I have added this issue to that list and also noted to try it on an older device.

**Comment by mochtu** [comment]
@kensodemann Thank you for attending to this and for keeping things well organised. Looking forward to v4 and Stencil. I'll try to give you feedback as well, then!

**Comment by jackyy415** [comment]
As we are experiencing the slowness of scrolling list on older iOS device, we have tried to remove the "outline: none" as suggested and the performance is greatly improved. 

As a Pro subscription user, we strongly urge Ionic team to remove this line asap. As we use the "Deploy" services to deploy the update, we have no way to intercept the build process. Thus, the mentioned line could not be removed manually during the build in the Cloud.

If your team is reluctant to remove the line, please either suggest ways to override that css line or we will seek for other framework. We have received many complaints from iOS users about the performance issue for scroll list and it is affecting our business.

**Comment by kevinmerckx** [comment]
@jackyy415 We used a script hook to remove those CSS lines. Here is how we did:

In your config.xml

```
<hook src="scripts/clean-ios-css.js" type="after_prepare" />
```

Our clean-ios-css.js code looks like:

```
const fs = require('fs');
const tasks = [{
  file: 'platforms/ios/www/build/main.css',
  toRemove: ':active,:focus{outline:0}'
}, {
  file: 'platforms/ios/www/build/main.css',
  toRemove: `:focus,
:active {
  outline: none;
}`
}, {
  file: 'www/build/main.css',
  toRemove: `:focus,
:active {
  outline: none;
}`
}];

function clean() {
  console.log('clean-ios-css: Cleaning starts');
  tasks.forEach(task => {
    if (!fs.existsSync(task.file)) {
      return;
    }
    const data = fs.readFileSync(task.file, 'utf8');
    const result = '/* cleaned by clean-ios-css hook */' + data.replace(new RegExp(task.toRemove, 'g'), '');
    fs.writeFileSync(task.file, result, 'utf8');
  });
  console.log('clean-ios-css: Cleaning done');
}

module.exports = function(context) {
  const deferral = context.requireCordovaModule('q').defer();
  clean();

  setTimeout(() => {
    deferral.resolve();
  }, 0);

  return deferral.promise;
}
```

**Comment by jackyy415** [comment]
@kevinmerckx Thanks a lot. Where should I place this file to? Does it work when I try to use the deploy service of Ionic?

**Comment by kevinmerckx** [comment]
@jackyy415 We've put the file under a `scripts/` folder at the root directory of our project but it can be wherever you want: it won't be built in your app, it's just a helper script that is ran after a build.

It should work with the deploy service of Ionic.

**Comment by jackyy415** [comment]
@kevinmerckx Thanks a lot. We have tried and it works.

**Comment by oddcb** [comment]
So very subjective, but it seems this also improves the click lag on my old iPad 3 Retina. I've no idea on how to measure this (besides perhaps a video), but after adding the script by @kevinmerckx  it seems my list of clickable items in a split pane is responding much faster.

**Comment by Tankatronic** [comment]
+1

I also encountered this issue. It seems to be causing excessive recalculating styles which is causing the slowdown to occur. All of my virtual scroll items were causing major FPS loss when interacted with and removing the aforementioned CSS rule resolved my issue. I am using an iPad Air 2.

**Comment by basvdijk** [comment]
I experienced the same issue on an iPad 3. When emulating it works fine but on the real devices it stuttered. After applying the script of @kevinmerckx the scrolling got significant smoother. Next week I will try WKWebView Engine to see if it works on that as well.

**Comment by luckylooke** [comment]
I think it should be fixed by this replacement:
```
:focus, input:active, textarea:active, select:active, button:active, a:active { outline: none; }
```

My temporary fix:
ionic-fixes.js
```
/*

	This script fixes performance issue on ios platfrom causing by ionic style:

	:focus,
	:active {
	  outline: none;
	}

	which causes huge style recalculations each touch start and touch end event on device causing bad performance of an app

	this script replace the rule by more adequate rule:

	:focus, input:active, textarea:active, select:active, button:active, a:active { outline: none; }

	this fix is actual until this issue remains opened:
	https://github.com/ionic-team/ionic/issues/13526
	related issue:
	https://github.com/ionic-team/ionic/issues/12733

*/



let path = require('path')
let fs = require('fs')

let filePath = path.resolve( __dirname, '../www/build/main.css')
// let filePath = path.resolve( __dirname, '../node_modules/ionic-angular/themes/util.scss')
let fileContent = fs.readFileSync( filePath, {
	encoding: 'utf8'
} )

fileContent = fileContent.replace(/:focus,\n:active {\n  outline: none;\n}/, ':focus, input:active, textarea:active, select:active, button:active, a:active { outline: none; }')
						 .replace(/:active,:focus{outline:0}/, ':focus,input:active,textarea:active,select:active,button:active,a:active{outline:0}') // minified version

fs.writeFileSync( filePath, fileContent )

console.log('ionic-fix applied')
```
and in package.json
```
  "scripts": {
    "ionic:build:after": "node ./build-hooks/ionic-fixes.js",
  }
```

**Comment by shawns582** [comment]
thanks @kevinmerckx and @luckylooke, removing/replacing those lines works to improve iOS scrolling for me too (iOS was previously an unusable platform -- scrolling has been a big problem for me since Ionic v1 and that alone has had me considering giving up on Ionic, although I love it otherwise). 

I am able to manually remove/replace those lines but for some reason cant get either of your scripts to automatically execute.  Generally for iOS I do a npm run ionic:build --prod and then use Xcode to archive or get it on my device.  What am I doing wrong? For @luckylooke 's script- If I do npm run ionic:build:after before I open Xcode it tells me the fix was applied but if I look at main.css those lines are still there.

Thanks!

**Comment by kevinmerckx** [comment]
@shawns582 if it tells you that the fix was applied (I assume that it prints out "ionic-fix applied") and you don't see the fix applied it's probably because the string to replace is not exactly matching what's in your main.css. You should try to modify the script to match what's in your main.css (it could depend on which version of ionic is used)

**Comment by laerciokonzen** [comment]
@luckylooke, I try you script, and check the ```mais.css``` at ```www/build```, it work fine. But the problem still happening. 
It has worked for you?

![image](https://user-images.githubusercontent.com/2004796/34695918-d1ad32bc-f4b3-11e7-8e0b-91004581fa1b.png)

**Comment by luckylooke** [comment]
@laerciokonzen, yes it worked for me, try real device, maybe sims dont have the same problem.
@shawns582 "ionic-fix applied" is just notification that script has been executed.. search in your main.css for "outline" and check if it match the regexp in my script, maybe there is a slight difference dependant on ionic version.

Problematic css rule is `:active { outline: none; }` which is generally aplied to all elements and causes perf problems, because it extends and multiply recalculations of whole page

**Comment by shawns582** [comment]
thanks @luckylooke @kevinmerckx  it turns out when I pasted the script above into a file it had an extra return before the .replace for the minified version so it was not working, but now it is. 

Relieved that this makes iOS usable! Hoping that the Ionic team will incorporate it is asap so others dont struggle with this.

**Comment by scottopolis** [comment]
Just wanted to add that I was seeing major issues with the slides on my iPad, and this fix solved it. @Bluestart83 you are a genius, thanks so much!

**Comment by RhinoLance** [comment]
@luckylooke I just wanted to add my heart felt thanks for your research and resolution.  After a significant development period, my app was unusable under iOS 10.  Your fix solved it.  Thank-you.

This is a major bug.  The consequences of which are significant for any reasonably sized app targeting iOS.  The Ionic team really should push this out as a fix to v3 asap.  I simply can't understand why they would leave this issue out there for everyone starting a new project for the last four months!

To leave on a happy note though, @luckylooke, you rock!

**Comment by sarahtully** [comment]
Thank you so much @kevinmerckx @luckylooke this resolved my issues, I wish I came across this solution earlier but you both saved me additional hours of racking my brain. Kudos!

**Comment by BuddyLReno** [comment]
This fixed an issue we were experiencing in our app as well. Thanks for the helpful script @kevinmerckx!

**Comment by fuentes010** [comment]
Thank you @kevinmerckx @luckylooke your proposed solution fixed my issues.
BTW I'm using [luckylooke script](https://github.com/ionic-team/ionic/issues/12733#issuecomment-347590079)

**Comment by juanjoseadan** [comment]
The hook created by @kevinmerckx works like a charm. Thank you!

**Comment by arupnayak** [comment]
> @jackyy415 We use a script hook to remove those CSS lines. We use `after_prepare` because it will be ran after `run`, `build` etc.. Here is how we did:
> 
> In your config.xml
> 
> ```
> <hook src="scripts/clean-ios-css.js" type="after_prepare" />
> ```
> Our clean-ios-css.js code looks like:
> 
> ```
> const fs = require('fs');
> const tasks = [{
>   file: 'platforms/ios/www/build/main.css',
>   toRemove: ':active,:focus{outline:0}'
> }, {
>   file: 'platforms/ios/www/build/main.css',
>   toRemove: `:focus,
> :active {
>   outline: none;
> }`
> }, {
>   file: 'www/build/main.css',
>   toRemove: `:focus,
> :active {
>   outline: none;
> }`
> }];
> 
> function clean() {
>   console.log('clean-ios-css: Cleaning starts');
>   tasks.forEach(task => {
>     if (!fs.existsSync(task.file)) {
>       return;
>     }
>     const data = fs.readFileSync(task.file, 'utf8');
>     const result = '/* cleaned by clean-ios-css hook */' + data.replace(new RegExp(task.toRemove, 'g'), '');
>     fs.writeFileSync(task.file, result, 'utf8');
>   });
>   console.log('clean-ios-css: Cleaning done');
> }
> 
> module.exports = function(context) {
>   const deferral = context.requireCordovaModule('q').defer();
>   clean();
> 
>   setTimeout(() => {
>     deferral.resolve();
>   }, 0);
> 
>   return deferral.promise;
> }
> ```

My script is working and it removed the css from main.css after prepare. But still scroll is slow in virtual list.
