### ISSUE TITLE
webpackJsonp is not defined

### ISSUE THREAD

**Issue by ayozebarrera** [ionic-team/ionic#12889]
**Ionic version:** 
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...** 
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
Just in case you don't know guys...

API docs are giving an Uncaught ReferenceError: webpackJsonp is not defined and the demo device is empty (black screen)

**Expected behavior:**
See the demo device content

**Steps to reproduce:**
Go to https://ionicframework.com/docs/api/components/modal/ModalController/ and check the device

Amazing job btw :heart:

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I believe this has been fixed. Can you please verify. I will re-open if it is not working for you.

Thank you for using Ionic

**Comment by barocsi** [comment]
Nope.

```
Runtime Error
webpackJsonp is not defined
Stack
ReferenceError: webpackJsonp is not defined
    at http://localhost:8100/build/main.js:1:1
```

Ionic Framework: ^3.6.1
Ionic Native: 2.4.1
Ionic App Scripts: 2.1.4
Angular Core: 4.1.3
Angular Compiler CLI: 4.1.3
Node: 8.2.1

**Comment by barocsi** [comment]
add <script src="build/vendor.js"></script> to index.html before main.js

**Comment by kensodemann** [comment]
@barocsi - where are you seeing this? I checked the link above and it appears to be fine.

**Comment by barocsi** [comment]
Just migrating my old ionic2 project so its resolved by updating the html, sorry.

**Comment by jmchaves** [comment]
I just updated ionic on my app and I got the same error:
Runtime Error
webpackJsonp is not defined
ReferenceError: webpackJsonp is not defined
    at http://localhost:8100/build/main.js:1:1
Ionic Framework: ^3.7.0
Ionic Native: ^2.9.0
Ionic App Scripts: 3.0.0
Angular Core: ^4.4.3
Angular Compiler CLI: ^4.4.3
Node: 8.2.1

After adding: <script src="build/vendor.js"></script> to index.html before main.js
It works, but once I run the command ionic serve again, it deletes vendor.js from the index.html.

Please help me with this.

**Comment by bashisha** [comment]
barosci, how did you migrate your old project?

**Comment by anjildhamala** [comment]
This is still an issue with android 4.4. It might be the same issue with ios 9. I see the white screen of death and "webpackJsonp is not defined".

**Comment by kensodemann** [comment]
@anjildhamala - can you post a link to your either your project's repo or if that is not possible (private repo for example) to a repo of a sample application that duplicates the issue?

**Comment by AshishAhuja124** [comment]
yaa <script src="build/vendor.js"></script> works .. for me..tq

**Comment by godenji** [comment]
Workaround does not work as `ionic serve` overwrites `index.html` *without* `<script src="build/vendor.js"></script>`

**Comment by NecroMan** [comment]
Update you src/index.html, not builded in www folder.

**Comment by godenji** [comment]
@NecroMan k, that preserves `vendor.js`, but now get:

> Cannot find module "ionic-native"

This is launching browser via `ionic serve`.

Might need to `ionic cordova platform add browser` (blew away old install, migrating to latest Ionic + Angular5).

**Comment by godenji** [comment]
k, all set, needed to add cordova plugins -- thanks for the `src/index.html` tip.

**Comment by Tactless7** [comment]
Hello guys, 
I got this error  "webpackjsonp is not defined" and get a blank screen with emulator Android 4.4, 5.0 and 5.1. Do you know why ?
Also on Android Lollipop, some users can run the app and others stay stucked on the splashscreen/blank screen.


Ionic Framework: 3.20.0
Ionic Native: 4.4.0
Ionic App Scripts: 3.1.7
Angular Core: 5.0.1
Angular Compiler CLI: 5.0.1
Node: 8.4.0

**Comment by cmartin81** [comment]
I also get the error "Uncaught ReferenceError: webpackJsonp is not defined" on Android 4.4.4
Anyone how know how to fix this?

**Comment by atheerahassan** [comment]
still getting "webpackjsonp is not defined" error and white blank screen with Android 5.0 
and <script src="build/vendor.js"></script> is already in my index.html

**Comment by k00na** [comment]
@atheerahassan , same here. what's the deal with this? anyone knows?

**Comment by Ramachandrajoshi** [comment]
@atheerahassan ,Same here. white screen problem on android 5.0

**Comment by atheerahassan** [comment]
@Ramachandrajoshi @k00na tried the solutions they gave but still to no avail. does upgrading android version gets rid of this error, i wonder.

**Comment by Ramachandrajoshi** [comment]
Yes on latest devices it is working fine. Not giving any error.

**Comment by Ramachandrajoshi** [comment]
Fixed.
In my case route cause of the problem is:
we have modified some code on IonicImageLoader Plugin.
which we have written the code is in ES6 format.
![screen shot 2018-08-13 at 2 49 28 pm](https://user-images.githubusercontent.com/14068607/44023840-32c8c0ac-9f09-11e8-8d98-07ed5ff464fb.png)

so If anyone getting the same problem look into the error above that and fix those at first place.
