### ISSUE TITLE
ion-button in ion-navbar does not pick up bar-button style classes in custom components

### ISSUE THREAD

**Issue by malina-kirn** [ionic-team/ionic#13637]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[ x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request

**Current behavior:**
When an ion-button is embedded in an ion-navbar, it picks up several bar-button style classes (`bar-button`, `bar-button-{platform}`, `bar-button-default`, and `bar-button-default-{platform}`). However, if the button is defined in a custom component, or if a custom component that includes an ion-navbar embeds a button using `<ng-content>`, the classes and corresponding style rules are not applied to the button.

**Expected behavior:**
An ion-button embedded in an ion-navbar should acquire bar-button style classes, even when the ion-navbar or ion-button is defined in a custom component.

**Steps to reproduce:**
Create an Angular component named custom-navbar. Define the HTML for the custom component as:

```
<ion-navbar>
  <ion-buttons>
    <button ion-button>Correct Style</button>
    <ng-content></ng-content>
  </ion-buttons>
</ion-navbar>
```

Create an Ionic page. Use custom-navbar and add embedded content of an ion-button using HTML like:

```
<ion-header>
  <custom-navbar>
    <button ion-button>Incorrect Style</button>
  </custom-navbar>
</ion-header>
```

Inspecting the source, you'll see the classes applied to the "Correct Style" button include bar-button, bar-button-md (assuming browser), bar-button-default, and bar-button-default-md. These classes are not applied to the "Incorrect Style" button. This can be worked around by applying the style classes manually.

This occurs in reverse, as well. To reproduce, create an Angular component named custom-button. Define the HTML for the custom component as:

```
<button ion-button>Incorrect Style</button>
```

Create an Ionic page. Use custom-button in an ion-navbar using HTML like:

```
<ion-header>
  <ion-navbar>
    <ion-buttons>
      <button ion-button>Correct Style</button>
      <custom-button></custom-button>
    </ion-buttons>
  </ion-navbar>
</ion-header>
```

My primary motivation for this pattern is that I have a header button with moderately complex logic that's re-used across all the main pages of my app. I wanted to consolidate this logic in one custom component.

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.3.0 ios 4.4.0
    Ionic Framework    : ionic-angular 3.8.0

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.1
    ios-sim           : 6.0.0
    Node              : v8.1.4
    npm               : 5.5.1
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : /Users/mkirn/Library/Android/sdk

Misc:

    backend : pro
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by malina-kirn** [comment]
Project is [here](https://github.com/malina-kirn/Ionic-Navbar-Button-Classes-Bug), use ionic serve to see the buttons rendered with correct and incorrect style classes applied.

The repository includes a [screenshot](https://github.com/malina-kirn/Ionic-Navbar-Button-Classes-Bug/blob/master/screenshot.png) of the correct/incorrect styles, as well as the classes applied to the buttons (note the missing `bar-button-*` classes on the incorrectly styled buttons).

**Comment by kensodemann** [comment]
Thank-you. I will take a look at it.

**Comment by kensodemann** [comment]
Looking at the code that handles this in the upcoming `@ionic/core` release (which will be part of Ionic v4) this should no longer be an issue at that time. I will mark this as something to double check after the initial v4 release is complete.

**Comment by peterpeterparker** [comment]
@kensodemann look like the same issue exist with `ion-footer` and `ion-toolbar`. Does the v4 fix gonna solve this too?

Sample application https://github.com/peterpeterparker/my-basket-button

Ionic forum discussion https://forum.ionicframework.com/t/css-breaks-with-new-custom-component-what-is-best-practice

**Comment by JohnAReid** [comment]
@kensodemann Have a look at the following post - this is a issue that can be easily fixed in Ionic 3

https://forum.ionicframework.com/t/custom-components-missing-ionic-directives/126974

**Comment by manucorporat** [comment]
this Is not longer a problem with ionic 4

**Comment by Laroosta** [comment]
I too am looking for a solution. Currently I need to duplicate code on every page due to this issue and its not looking pretty.

**Comment by JohnAReid** [comment]
@Laroosta 

Have a read of this post - it explains how to add two imports to the component.module.ts file which fixes the problem.

https://forum.ionicframework.com/t/custom-components-missing-ionic-directives/126974

**Comment by all43** [comment]
Why it's closed?
The problem still exist and thousands still using v3.
I'm not a developer, so I don't know how to make a pull request.
But as I can see problem laying here:
https://github.com/ionic-team/ionic/blob/master/core/src/components/button/button.tsx

```
  componentWillLoad() {
    if (this.el.closest('ion-buttons')) {
      this.buttonType = 'bar-button';
    }
  }
```
Maybe it's possible to add type attribute as workaround?
