### ISSUE TITLE
<ion-item-options side="left"> appears on right side (Ionic4)

### ISSUE THREAD

**Issue by ghybs** [ionic-team/ionic#14293]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[X] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

The `<ion-item-options side="left">` buttons appear when swiping from right to left, as if the `side` attribute was ignored.
If another `<ion-item-options>` is present in the same `<ion-item-sliding>` element, all buttons are stacked on the right side.

**Expected behavior:**

Buttons in `<ion-item-options side="left">` element should appear on the left, i.e. when swiping from left to right.

**Steps to reproduce:**

1. Try swiping an item from left to right: nothing happens, even though some `<ion-item-options side="left">` element(s) have been specified in code.
2. Swipe an item from right to left: buttons appear, as if they had been specified with `side="right"`

**Related code:**
http://plnkr.co/edit/FsmXIxFOeAW4Z3MA3xHe?p=preview

```html
<ion-item-sliding>
  <ion-item>
    <ion-label>Item with left options only</ion-label>
  </ion-item>
  <ion-item-options side="left">
    <ion-item-option onClick="favorite(item)">Favorite</ion-item-option>
    <ion-item-option color="danger" onClick="share(item)">Share</ion-item-option>
  </ion-item-options>
</ion-item-sliding>
```

**Other information:**

Occurs since `@ionic/core` version 0.2.2 and 4.0.0-alpha.1 (current)

**Comment by brandyscarney** [comment]
Thanks for the issue! The values for `side` were renamed from `left` to `start` and `right` to `end`. I noticed we didn't have this included in the breaking changes so I added it here: https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md#item-options

I noticed that updating these in your plunker is not fixing them, but this should be working on the next alpha release.

**Comment by ghybs** [comment]
Hi,

Thank you for clearing things up!

I will be happy to test it in the next release.
For reference, here is an updated plunker with `"start"` and `"end"` values for `side` attribute:
http://plnkr.co/edit/GlD85AB62QlFisudQ7Ep?p=preview

BTW, I also noticed in the `item-sliding` component [README](https://github.com/ionic-team/ionic/blob/ea24ad677dc6381d873d845f564ca3d8663464e5/core/src/components/item-sliding/readme.md) that we still refer to "_right side_" and "_swip[ing] from right to left_", which I guess is reversed in RTL.

I can submit a PR to make the wording more explicit, e.g.:
> By default, the buttons are placed on the `"end"` side. This means that options are revealed when the sliding item is swiped from end to start, i.e. from right to left in LTR, but from left to right in RTL. To place them on the opposite side, so that they are revealed when swiping to the opposite direction, set the `side` attribute to `"start"` on the `ion-item-options` element.

Or maybe a table could be more suitable, as done in [`buttons` component README](https://github.com/ionic-team/ionic/blob/2c9d485d2dba1b3cd759a1a1c87bb02b6907ff14/core/src/components/buttons/readme.md) for example?

**Comment by ghybs** [comment]
> which I guess is reversed in RTL.

Looks like I was partially wrong:
When direction is set to `rtl`, buttons are now placed on the other side (i.e. on the left, irrespective of the `side` attribute value for now), but the swiping direction to reveal them is still the same, i.e. you have to swipe from right to left, which reveals… nothing until you reach the far left of the screen, where buttons are now placed.
http://plnkr.co/edit/PJRHOr91V9QNkMyn8NRt?p=preview

Should I open a separate bug report for this?

**Comment by brandyscarney** [comment]
@ghybs Good catch! If you'd like to create a PR I'd be happy to get it merged in. Whatever you think makes the most sense. I think a table would be helpful or we could link back to [item options](https://github.com/ionic-team/ionic/blob/master/core/src/components/item-options/readme.md). Although that is currently outdated too. :grin:
