### ISSUE TITLE
Switch to the home page again, 'onViewDidEnter()'function does not perform 

### ISSUE THREAD

**Issue by wangli1992** [ionic-team/ionic#16465]
# Bug Report

**Ionic Info**
 "@ionic/angular": "4.0.0-beta.15

```
insert the output from ionic info here
```

**Describe the Bug**
For example， from  contact page switch to home page ‘onViewDidEnter()’ function does not perform ，Only come in for the first time to perform ，why？？

**Steps to Reproduce**
1. ionic serve 
2. Click on 'contact'
3. switch to home page
4. in the home page  ‘onViewDidEnter()’ function does not perform

**Related Code**

**Expected Behavior**

**Additional Context**
List any other information that is relevant to your issue. Stack traces, related issues, suggestions on how to fix, Stack Overflow links, forum links, screenshots, OS if applicable, etc.

**Comment by UVKApps** [comment]
With Ionic 4 the ionic lifecycle hooks for views have been removed, you should use the angular lifecycle hooks instead. ngOnInit() etc.

However angular only provides hooks upon creating and destroying a view, no hook for navigation to a cached view like onViewDidEnter(). Would be great if that could be readded by the ionic team.

For now i solved by listening to routing events like this: 
`constructor(private router: Router) {
    this.router.events.subscribe((val: any): void => {
      if(val instanceof NavigationEnd){
        if(val.urlAfterRedirects.includes('home') ){
          this.onViewDidEnter();
        }
      }
    })
  }`

**Comment by KevinKelchen** [comment]
Are you using the correct method/event name? You refer to `onViewDidEnter()` but I think it may be called `ionViewDidEnter()`. Perhaps it's being conflated with how Angular events begin with "on?"

Most Ionic lifecycle hooks are still present. I continue to find them to be useful for scenarios Angular doesn't support. For example, if you need something to happen when revisiting an already initialized `Page` (e.g., using `ion-back-button` or browser back button, revisiting the same URL at times), you can use `ionViewWillEnter()`.

[Comment on remaining lifecycle events](https://github.com/ionic-team/ionic/issues/15806#issuecomment-425651642)
[Latest definition of standard lifecycle events in Ionic source code](https://github.com/ionic-team/ionic/blob/master/core/src/index.ts)
[Latest definition of Modal lifecycle events in Ionic source code (bottom of this file](https://github.com/ionic-team/ionic/blob/master/core/src/components/modal/modal.tsx)

**Comment by wangli1992** [comment]
> Are you using the correct method/event name? You refer to `onViewDidEnter()` but I think it may be called `ionViewDidEnter()`. Perhaps it's being conflated with how Angular events have "on" in the event name or event interfaces begin with "On?"
> 
> Most Ionic lifecycle hooks are still present. I continue to find them to be useful for scenarios Angular doesn't support. For example, if you need something to happen when revisiting an already initialized `Page` (e.g., using `ion-back-button` or browser back button, revisiting the same URL at times), you can use `ionViewWillEnter()`.
> 
> [Comment on remaining lifecycle events](https://github.com/ionic-team/ionic/issues/15806#issuecomment-425651642)
> [Latest definition of standard lifecycle events in Ionic source code](https://github.com/ionic-team/ionic/blob/master/core/src/index.ts)
> [Latest definition of Modal lifecycle events in Ionic source code (bottom of this file)](https://github.com/ionic-team/ionic/blob/master/core/src/components/modal/modal.tsx)

 sorry ! spell wrong, wrote an 'i'

**Comment by wangli1992** [comment]
> With Ionic 4 the ionic lifecycle hooks for views have been removed, you should use the angular lifecycle hooks instead. ngOnInit() etc.
> 
> However angular only provides hooks upon creating and destroying a view, no hook for navigation to a cached view like onViewDidEnter(). Would be great if that could be readded by the ionic team.
> 
> For now i solved by listening to routing events like this:
> `
> 
> ```
> this.router.events.subscribe((val: any): void => {
>   if(val instanceof NavigationEnd){
>     if(val.urlAfterRedirects.includes('home') ){
>       this.onViewDidEnter();
>     }
>   }
> })
> ```
> `

thanks,I according to you this kind of writing, when once again to enter the home page，ion-slides，no longer automatically round，The code below：
html ：on-slides #slides pager="true" [options]="slideOpts" mode="ios">
    <ion-slide>
      <img src="assets/images/guide1.jpg" style="width:100%;height:180px;" />
    </ion-slide>
    <ion-slide>
      <img src="assets/images/guide2.jpg" style="width:100%;height:180px;" />
    </ion-slide>
    <ion-slide>
      <img src="assets/images/guide3.jpg" style="width:100%;height:180px;" />
    </ion-slide>
  </ion-slides>
ts：slideOpts = {
        effect: 'flip',
        loop: true,
        slidesPerView: 'auto',
        autoplay: true,
        speed: 300
    };

**Comment by paulstelzer** [comment]
ionViewDidEnter is the correct one, please see also my medium article about the lifecycle hooks -> https://medium.com/@paulstelzer/ionic-4-and-the-lifecycle-hooks-4fe9eabb2864
