### ISSUE TITLE
ionic 4 icon not found

### ISSUE THREAD

**Issue by haythoo** [ionic-team/ionic#17239]
# Support Question

Hi,
after upgrading from rc1 to ionic 4 stable, I noticed some icons are not working!!!
`
GET http://localhost:8100/svg/ios-notifications.svg 404 (Not Found) zone.js:1152 
GET http://localhost:8100/svg/ios-home.svg 404 (Not Found) zone.js:1152 
GET http://localhost:8100/svg/ios-wallet.svg 404 (Not Found) zone.js:1152 
GET http://localhost:8100/svg/ios-contact.svg 404 (Not Found) zone.js:1152 

`

I created a new black project, but the also on the new project I'm having the same issue. I checked the angular.json file, and I found this:
` "assets": [
              {
                "glob": "**/*",
                "input": "src/assets",
                "output": "assets"
              },
              {
                "glob": "**/*.svg",
                "input": "node_modules/ionicons/dist/ionicons/svg",
                "output": "./svg"
              },
              "src/manifest.json"
            ],`

I checked again, some icons are working and some are not:

` 
<ion-icon name="notifications"></ion-icon>

    <ion-icon name="home"></ion-icon>

    <ion-icon name="albums"></ion-icon>

    <ion-icon name="notifications-outline"></ion-icon>

    <ion-icon name="wallet"></ion-icon>

    <ion-icon name="contact"></ion-icon>

    <ion-icon name="contacts"></ion-icon>

    <ion-icon name="planet"></ion-icon>
`

not working:
- notifications
- home
- wallet
- contact

Working:
- albums
- notifications-outline
- contacts
- planet

**Comment by mariusbolik** [comment]
Had the same problem. Like you said you have to create an new blank Ionic project. Then copy the `angular.json` from the blank project to your existing project (replace the old `angular.json`). Then delete your `node_modules` folder and run `npm install` again.
This should fix the problem.

**Comment by jrayga** [comment]
> Had the same problem. Like you said you have to create an new blank Ionic project. Then copy the `angular.json` from the blank project to your existing project (replace the old `angular.json`). Then delete your `node_modules` folder and run `npm install` again.
> This should fix the problem.

Hi Good day,

I've already done this with my project but some icons are still missing on ios.
```
{
  "$schema": "./node_modules/@angular-devkit/core/src/workspace/workspace-schema.json",
  "version": 1,
  "defaultProject": "app",
  "newProjectRoot": "projects",
  "projects": {
    "app": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
      "schematics": {},
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "www",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              {
                "glob": "**/*",
                "input": "src/assets",
                "output": "assets"
              },
              {
                "glob": "**/*.svg",
                "input": "node_modules/ionicons/dist/ionicons/svg",
                "output": "./svg"
              }
            ],
            "styles": [
              {
                "input": "src/theme/variables.scss"
              },
              {
                "input": "src/global.scss"
              },
              {
                "input": "node_modules/angular-instantsearch/bundles/instantsearch.min.css"
              },
              {
                "input": "node_modules/angular-instantsearch/bundles/instantsearch-theme-algolia.min.css"
              }
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                }
              ]
            },
            "ci": {
              "progress": false
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "app:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "app:build:production"
            },
            "ci": {
              "progress": false
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "app:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "styles": [],
            "scripts": [],
            "assets": [
              {
                "glob": "favicon.ico",
                "input": "src/",
                "output": "/"
              },
              {
                "glob": "**/*",
                "input": "src/assets",
                "output": "/assets"
              }
            ]
          },
          "configurations": {
            "ci": {
              "progress": false,
              "watch": false
            }
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "ionic-cordova-build": {
          "builder": "@ionic/angular-toolkit:cordova-build",
          "options": {
            "browserTarget": "app:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "app:build:production"
            }
          }
        },
        "ionic-cordova-serve": {
          "builder": "@ionic/angular-toolkit:cordova-serve",
          "options": {
            "cordovaBuildTarget": "app:ionic-cordova-build",
            "devServerTarget": "app:serve"
          },
          "configurations": {
            "production": {
              "cordovaBuildTarget": "app:ionic-cordova-build:production",
              "devServerTarget": "app:serve:production"
            }
          }
        }
      }
    },
    "app-e2e": {
      "root": "e2e/",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "app:serve"
          },
          "configurations": {
            "ci": {
              "devServerTarget": "app:serve:ci"
            }
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": "e2e/tsconfig.e2e.json",
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  },
  "cli": {
    "defaultCollection": "@ionic/angular-toolkit"
  },
  "schematics": {
    "@ionic/angular-toolkit:component": {
      "styleext": "scss"
    },
    "@ionic/angular-toolkit:page": {
      "styleext": "scss"
    }
  }
}
```

**Comment by stephenzeng** [comment]
Having the same problem. Added a simple ion-back-button in the toolbar but it is showing anything. Can confirm that the ios-arrow-back.svg file is in the www/svg folder.

**Comment by stephenzeng** [comment]
> > Had the same problem. Like you said you have to create an new blank Ionic project. Then copy the `angular.json` from the blank project to your existing project (replace the old `angular.json`). Then delete your `node_modules` folder and run `npm install` again.
> > This should fix the problem.
> 
> Hi Good day,
> 
> I've already done this with my project but some icons are still missing on ios.
> 
> ```
> {
>   "$schema": "./node_modules/@angular-devkit/core/src/workspace/workspace-schema.json",
>   "version": 1,
>   "defaultProject": "app",
>   "newProjectRoot": "projects",
>   "projects": {
>     "app": {
>       "root": "",
>       "sourceRoot": "src",
>       "projectType": "application",
>       "prefix": "app",
>       "schematics": {},
>       "architect": {
>         "build": {
>           "builder": "@angular-devkit/build-angular:browser",
>           "options": {
>             "outputPath": "www",
>             "index": "src/index.html",
>             "main": "src/main.ts",
>             "polyfills": "src/polyfills.ts",
>             "tsConfig": "src/tsconfig.app.json",
>             "assets": [
>               {
>                 "glob": "**/*",
>                 "input": "src/assets",
>                 "output": "assets"
>               },
>               {
>                 "glob": "**/*.svg",
>                 "input": "node_modules/ionicons/dist/ionicons/svg",
>                 "output": "./svg"
>               }
>             ],
>             "styles": [
>               {
>                 "input": "src/theme/variables.scss"
>               },
>               {
>                 "input": "src/global.scss"
>               },
>               {
>                 "input": "node_modules/angular-instantsearch/bundles/instantsearch.min.css"
>               },
>               {
>                 "input": "node_modules/angular-instantsearch/bundles/instantsearch-theme-algolia.min.css"
>               }
>             ],
>             "scripts": []
>           },
>           "configurations": {
>             "production": {
>               "fileReplacements": [
>                 {
>                   "replace": "src/environments/environment.ts",
>                   "with": "src/environments/environment.prod.ts"
>                 }
>               ],
>               "optimization": true,
>               "outputHashing": "all",
>               "sourceMap": false,
>               "extractCss": true,
>               "namedChunks": false,
>               "aot": true,
>               "extractLicenses": true,
>               "vendorChunk": false,
>               "buildOptimizer": true,
>               "budgets": [
>                 {
>                   "type": "initial",
>                   "maximumWarning": "2mb",
>                   "maximumError": "5mb"
>                 }
>               ]
>             },
>             "ci": {
>               "progress": false
>             }
>           }
>         },
>         "serve": {
>           "builder": "@angular-devkit/build-angular:dev-server",
>           "options": {
>             "browserTarget": "app:build"
>           },
>           "configurations": {
>             "production": {
>               "browserTarget": "app:build:production"
>             },
>             "ci": {
>               "progress": false
>             }
>           }
>         },
>         "extract-i18n": {
>           "builder": "@angular-devkit/build-angular:extract-i18n",
>           "options": {
>             "browserTarget": "app:build"
>           }
>         },
>         "test": {
>           "builder": "@angular-devkit/build-angular:karma",
>           "options": {
>             "main": "src/test.ts",
>             "polyfills": "src/polyfills.ts",
>             "tsConfig": "src/tsconfig.spec.json",
>             "karmaConfig": "src/karma.conf.js",
>             "styles": [],
>             "scripts": [],
>             "assets": [
>               {
>                 "glob": "favicon.ico",
>                 "input": "src/",
>                 "output": "/"
>               },
>               {
>                 "glob": "**/*",
>                 "input": "src/assets",
>                 "output": "/assets"
>               }
>             ]
>           },
>           "configurations": {
>             "ci": {
>               "progress": false,
>               "watch": false
>             }
>           }
>         },
>         "lint": {
>           "builder": "@angular-devkit/build-angular:tslint",
>           "options": {
>             "tsConfig": [
>               "src/tsconfig.app.json",
>               "src/tsconfig.spec.json"
>             ],
>             "exclude": [
>               "**/node_modules/**"
>             ]
>           }
>         },
>         "ionic-cordova-build": {
>           "builder": "@ionic/angular-toolkit:cordova-build",
>           "options": {
>             "browserTarget": "app:build"
>           },
>           "configurations": {
>             "production": {
>               "browserTarget": "app:build:production"
>             }
>           }
>         },
>         "ionic-cordova-serve": {
>           "builder": "@ionic/angular-toolkit:cordova-serve",
>           "options": {
>             "cordovaBuildTarget": "app:ionic-cordova-build",
>             "devServerTarget": "app:serve"
>           },
>           "configurations": {
>             "production": {
>               "cordovaBuildTarget": "app:ionic-cordova-build:production",
>               "devServerTarget": "app:serve:production"
>             }
>           }
>         }
>       }
>     },
>     "app-e2e": {
>       "root": "e2e/",
>       "projectType": "application",
>       "architect": {
>         "e2e": {
>           "builder": "@angular-devkit/build-angular:protractor",
>           "options": {
>             "protractorConfig": "e2e/protractor.conf.js",
>             "devServerTarget": "app:serve"
>           },
>           "configurations": {
>             "ci": {
>               "devServerTarget": "app:serve:ci"
>             }
>           }
>         },
>         "lint": {
>           "builder": "@angular-devkit/build-angular:tslint",
>           "options": {
>             "tsConfig": "e2e/tsconfig.e2e.json",
>             "exclude": [
>               "**/node_modules/**"
>             ]
>           }
>         }
>       }
>     }
>   },
>   "cli": {
>     "defaultCollection": "@ionic/angular-toolkit"
>   },
>   "schematics": {
>     "@ionic/angular-toolkit:component": {
>       "styleext": "scss"
>     },
>     "@ionic/angular-toolkit:page": {
>       "styleext": "scss"
>     }
>   }
> }
> ```

Try run ionic build, then go to www/svg folder to make sure the said missing icons svg files are there. 

Then run ionic serve. If the icon is still not showing, try Ctrl + F5, or clear the browser cache then refresh.

**Comment by paulstelzer** [comment]
And please don't forget to clear the browser cache
