### ISSUE TITLE
bug: Swipe right to open side menu crashes app.

### ISSUE THREAD

**Issue by liquidcms** [ionic-team/ionic#18927]
# Bug Report

**Ionic version:**
[x] 4.6.2

**Current behavior:**

When I start the app and then immediately swipe right to open the side menu; the app crashes. The menu does not open, none of the nav work anymore. It appears the app has frozen.

If, the first time i open the side menu is with the ion-menu-button in my header; then I can no longer get the app to crash by swiping right. It only occurs if swipe is the first time I open the side menu.

I used to (Ionic 1) use GapDebug to test code running on real device; but that tool is no longer available and I have had no luck finding something that replaces this ability. I am not able to re-create this issue in Chrome.

**Expected behavior:**

Swipe to open side menu should open the side menu.

**Steps to reproduce:**

see above.

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.1 (C:\Users\Peter\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Capacitor:

   Capacitor CLI   : 1.0.0-beta.24
   @capacitor/core : 1.0.0-beta.24

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 7 other plugins)

Utility:

   cordova-res : 0.3.0
   native-run  : 0.2.3

System:

   Android SDK Tools : 26.1.1 (C:\android-sdk)
   NodeJS            : v10.13.0 (D:\Program Files\nodejs\node.exe)
   npm               : 6.9.2
   OS                : Windows 7

```

**Comment by liquidcms** [comment]
If swipe right to open side menu does not work reliably; perhaps this feature should be disabled?

**Comment by liamdebeasi** [comment]
Thanks for the issue. Does this happen on the side menu starter app?

**Comment by liquidcms** [comment]
Nope. Can't get it to occur on the side menu starter app. Guess that means something in my app. Will need to figure out how to debug app on real devices.. :(

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Can you provide a repo with the code required to reproduce this issue?

**Comment by liquidcms** [comment]
Parts of my code are from this start app: https://ionicthemes.com/product/ionic4-full-starter-app. I'll try their starter app and see if it shows the issue. After that, I'll put a repo up with my code. I am not really sure what is required to be in the repo to make an ionic app buildable; any tips? The app is on github now actually; but private.
![liquidcms_qleva-app](https://user-images.githubusercontent.com/355815/62251198-f9f02800-b3bc-11e9-8631-8d5581d525d7.png)

**Comment by liquidcms** [comment]
Hmm.. I can't seem to repeat the problem now. Will keep an eye on it and post my code if I can repeat it later. Thank you for trying to help me get to the bottom of this.

**Comment by lincolnthree** [comment]
I have also been experiencing this behavior on Android w/Capacitor. Not sure why yet. I cannot reproduce it in the desktop browser.

**Comment by lincolnthree** [comment]
Okay, I was able to get this to happen while the Chrome debugger was open, @liamdebeasi -- here's the stack trace from the animation module when sliding out the menu caused the crash. 

````
animation-7ed5bc6a.js:587 Uncaught TypeError: Failed to set the 'currentTime' property on 'Animation': The provided double value is non-finite.
    at animation-7ed5bc6a.js:587
    at Array.forEach (<anonymous>)
    at setAnimationStep (animation-7ed5bc6a.js:586)
    at Object.progressEnd (animation-7ed5bc6a.js:690)
    at animation-7ed5bc6a.js:679
    at Array.forEach (<anonymous>)
    at Object.progressEnd (animation-7ed5bc6a.js:678)
    at class_1.push../node_modules/@ionic/core/dist/esm-es5/ion-menu_4-ios.entry.js.class_1.onEnd (ion-menu_4-ios.entry.js:369)
    at onEnd (ion-menu_4-ios.entry.js:113)
    at pointerUp (index-624eea58.js:532)
````

**Comment by lincolnthree** [comment]
And this is the line it's referencing:

````
 var setAnimationStep = function (step) {
        step = Math.min(Math.max(step, 0), 0.999);
        if (supportsWebAnimations) {
            webAnimations.forEach(function (animation) {
--->                animation.currentTime = animation.effect.getComputedTiming().delay + (getDuration() * step);
                animation.pause();
            });
        }
        else {
            var animationDelay = getDelay() || 0;
            var animationDuration_1 = "-" + (animationDelay + (getDuration() * step)) + "ms";
            elements.forEach(function (element) {
                if (_keyframes.length > 0) {
                    setStyleProperty(element, 'animation-delay', animationDuration_1);
                    setStyleProperty(element, 'animation-play-state', 'paused');
                }
            });
        }
    };
````

**Comment by liamdebeasi** [comment]
Can you update to the latest version of Ionic? This issue has already been fixed.

**Comment by liquidcms** [comment]
Do you know what version it was fixed in? I rarely see the issue any more. I am running 4.7.4.

**Comment by liamdebeasi** [comment]
It was fixed in Ionic 4.10 (it started happening in 4.8/4.9 I believe).

**Comment by liquidcms** [comment]
Ah, ok, perhaps not the same issue then, as I reported it in 4.6.

**Comment by liamdebeasi** [comment]
Might be a different issue, yeah. Does the original issue still exist in the latest version of Ionic?

**Comment by lincolnthree** [comment]
@liamdebeasi Sure. I encountered this on 4.11.1. You want me to try on Beta.0, I assume?

**Comment by liamdebeasi** [comment]
Ah sorry didn't realize you were on 4.11.1. Are the steps to reproduce the issue the same?

**Comment by lincolnthree** [comment]
@liamdebeasi No worries. Yes. Pretty much just open the app, try the menu (drag it in and out a few times, partially, fully, not sure which breaks it), and one out of a few times it will crash with that error. Of course I say that now and I've gotten it to break once after trying for the last 15 minutes.

**Comment by lincolnthree** [comment]
Twice.

**Comment by lincolnthree** [comment]
Okay, it seems more common when you use Pixel 2 XL device mode in Chrome DevTools. Drag the menu open, then holding the mouse button down, drag the menu closed so that the mouse goes off the edge of the screen, then back on moving from bottom left to top right. While moving in that direction, release the mouse before the menu is completely open again.

Trying to get a vid now.

**Comment by lincolnthree** [comment]
@liamdebeasi  Got a video of it, also tried to show as much of the console / source / elements as possible: https://youtu.be/RNCNVs7XBFU

One thing to note is that I have a `--width: 230px` set on the menu. It's within a side-pane layout. That's the only thing I can think of that's really "custom". The rest is just colors/gradients/etc.

**Comment by lincolnthree** [comment]
PS. Now that I know the gesture that causes this. I can get it to happen every time. Menu needs to be open. Grab near bottom edge. Drag in a rounded motion over bottom left corner of viewport, then round downward, hook back just slightly, and release.

**Comment by liamdebeasi** [comment]
Thanks for the additional info and video! It was very helpful. Can you try this dev build and let me know if the issue is fixed?

`npm i @ionic/angular@4.12.0-dev.201910171955.51969ca`

**Comment by lincolnthree** [comment]
@liamdebeasi I'm glad the video helped. Looks like that took care of it! I've gotten pretty good at reproducing "that gesture", and the issue seems to be resolved in your dev build. Kudos for all your great work btw.

V4 has been a big shift, but... the benefit is real. 

With more issues like this being resolved (and as I understand the inner workings better), this app is feeling more and more ready for prime time with each release.

**Comment by liamdebeasi** [comment]
Glad to hear everything is working, and glad to hear you're enjoying v4!

@liquidcms Can you try the dev build above, and let me know if it resolves the issue you are seeing?

**Comment by liquidcms** [comment]
I'll try it out but difficult to test as the problem happens very rarely with 4.7.

I am sure we are reporting the same problem though, so confident it has been cleared up. 

Thank you for looking at this.

**Comment by liamdebeasi** [comment]
I merged the fix in. This fix will be available in an upcoming release of Ionic. Thanks!

**Comment by teja8352** [comment]
> Thanks for the issue. Does this happen on the side menu starter app?

Yes, it's happening on the side menu starter app. When I tried to open the side menu for 2 to 3 times the whole application struck.



**Ionic Info**

```
Ionic:

   Ionic CLI                     : 5.2.7
   Ionic Framework               : @ionic/angular 4.9.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 15 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.2

System:

   Android SDK Tools : 26.1.1 (C:\Android\sdk)
   NodeJS            : v12.13.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.12.1
   OS                : Windows 10


```

**Comment by liquidcms** [comment]
I did see the issue again (it had been a while); but i was still on 4.7.4. Upgrading now to your 4.12 dev build above as it looks like release is still at 4.11.

gesture mentioned above: "Menu needs to be open. Grab near bottom edge. Drag in a rounded motion over bottom left corner of viewport, then round downward, hook back just slightly, and release." is certainly not the one i use to break this.

a few deprecated warnings now but otherwise app seems to be working as it was with 4.7.4; so will continue testing with your 4.12-dev and see if i can see lockup re-occur.
