### ISSUE TITLE
bug: On ion-toggle, toggle-inner does not adapt to height and width

### ISSUE THREAD

**Issue by rathodkaran07** [ionic-team/ionic#19868]
# Bug Report

**Ionic version:**

[x] **4.10**

**Current behavior:**

We can change height and width of a ion-toggle but toggle-inner does not adapt the respective height and width

Here is the styling that I am using:
```
<ion-toggle #onOffToggle mode='ios'></ion-toggle>
ion-toggle {
		--background: var(--color-red);
		--background-checked: var(--color-green);
		height: 20px;
		width: 50px;
	}
```
![image](https://user-images.githubusercontent.com/6977558/68451333-637d9f00-0214-11ea-9baa-3ba8bcda687c.png)

**Expected behavior:**

Inner circle should adapt to the respective height

Also by some way can I make toogle look like this?
![image](https://user-images.githubusercontent.com/6977558/68451418-b5bec000-0214-11ea-90cd-b951e90f64d9.png)

**Steps to reproduce:**

<ion-toggle #onOffToggle mode='ios'></ion-toggle>

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.2
   Ionic Framework               : @ionic/angular 4.10.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 5 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.9

System:

   Android SDK Tools : 26.1.1 (C:\Program Files\Android\android-sdk)
   NodeJS            : v12.13.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.12.0
   OS                : Windows 10

```

**Comment by mattsteve** [comment]
I've had this issue as well. Toggle customization is extremely lacking.

**Comment by C-racker** [comment]
+1

**Comment by rajiramamoorthi** [comment]
Any solution for the above issue

**Comment by mattsteve** [comment]
Here's my proposal based on what my team needs:

## Height

When the height of the toggle is manipulated, it should automatically resize the handle's width and height. It should also automatically reposition the checked version of the handle to the right of the toggle.

![ionToggleHeightSm](https://user-images.githubusercontent.com/34715493/76103750-3792e000-5fa0-11ea-88a2-05c6faf84b56.png)

## Width

When the width of the toggle is manipulated, the checked toggle handle should be positioned to the right of toggle.

![ionToggleWidthSm](https://user-images.githubusercontent.com/34715493/76103894-788af480-5fa0-11ea-9ccb-7a470edab99b.png)

## Inner Padding

With the assumption that the default `--inner-padding` value is 2px, this is what 0px would look like. Our team needs to control the relative size of the toggle handle to the background.

<img alt="ionToggleInnerPaddingSm" src="https://user-images.githubusercontent.com/34715493/76104074-bab43600-5fa0-11ea-8a86-0ddc55806c64.png">

## Handle Box Shadow

We need to be able to control the box shadow on the toggle handle in both checked and unchecked states.

![ionToggleHandleBoxShadowSm](https://user-images.githubusercontent.com/34715493/76104256-09fa6680-5fa1-11ea-8fcf-1e7f0ae1b7a5.png)

## Overflow

In our specific case, we need the box shadow on the handle to display outside the boundaries of the toggle background. So setting `--overflow` would control the overflow property on the `<div class="toggle-icon">` element.

<img alt="ionToggleOverflowSm" src="https://user-images.githubusercontent.com/34715493/76104356-34e4ba80-5fa1-11ea-9b08-4b56dec3472d.png">

## End Result

Our end result is this, assuming we put additional padding and border on the `ion-toggle` element for the outer border.

<img alt="toggles" src="https://user-images.githubusercontent.com/34715493/76104625-b4728980-5fa1-11ea-8ffd-cc2ed73aaf9e.png">

**Comment by BerthaBrenes** [comment]
The only "solution" for now is to use in the scss a zoom attribute.
Its like magic, but its not possible to customize

**Comment by rajiramamoorthi** [comment]
HI @brandyscarney 

Any update on this?

**Comment by brandyscarney** [comment]
Thank you for the issue, and thank you @mattsteve for the detailed requirements of your team. This was helpful! I've implemented your suggestions with some changes as part of the PR here: https://github.com/ionic-team/ionic/pull/21050

There is some new documentation for the customization added here (this will go live on the toggle API docs after we release): https://github.com/ionic-team/ionic/blob/master/core/src/components/toggle/readme.md#customization

This will be in the `5.1` release which is expected soon, but the following dev build can be used if you want to take a sooner look. Run one of the following commands based on your framework integration:

```bash
# core / vanilla JS
npm i @ionic/core@5.1.0-dev.202004292244.04ace4c --save

# angular
npm i @ionic/angular@5.1.0-dev.202004292244.04ace4c --save

# react
npm i @ionic/react@5.1.0-dev.202004292244.04ace4c --save
```

----------------------------------------------------------------------------------------

To respond to the original question of how to make a toggle with a power button / ON text, this can be done using pseudo-elements, by changing the `background` property, or a combination of the two. 

Because the `--background` and `--handle-background` variables set the `background` property, which is a shorthand, it can accept any value that the [background property](https://developer.mozilla.org/en-US/docs/Web/CSS/background) accepts.

Adding an image to the handle background:

```css
ion-toggle {
  --handle-background-checked: #fff url(/assets/power-icon.png) no-repeat center / contain;
}
```

![Screen Shot 2020-04-29 at 3 55 16 PM](https://user-images.githubusercontent.com/6577830/80640765-e3512d00-8a31-11ea-8e92-a1654ee28fa0.png)

Taking it a step further, we could use the `::before` or `::after` pseudo-elements to position text on top of the background.

```css
ion-toggle::before {
  position: absolute;

  top: 16px;
  left: 10px;

  content: "ON";

  color: white;
  font-size: 8px;

  z-index: 1;
}
```

![Screen Shot 2020-04-29 at 3 25 05 PM](https://user-images.githubusercontent.com/6577830/80640692-c3ba0480-8a31-11ea-9dee-25ad9de0e030.png)

In addition to that, I've created a Codepen showing how to re-create the native iOS on/off labels under Settings/Accessibility: https://codepen.io/brandyscarney/pen/YzyxeXa

Related issue: https://github.com/ionic-team/ionic/issues/20524

**Comment by vohrahul** [comment]
@brandyscarney Thanks for this update. Waiting for 5.1 release to use this. Any chance to also work with size? Like if I want a `100% width` ion-toggle, how do I do it?

**Comment by brandyscarney** [comment]
@vohrahul `5.1.0` was released last week so you can try this out now. 🙂 

Here's a Codepen with different customizations: https://codepen.io/brandyscarney/pen/NWGawmg

**Comment by vohrahul** [comment]
> @vohrahul `5.1.0` was released last week so you can try this out now. 
> 
> Here's a Codepen with different customizations: https://codepen.io/brandyscarney/pen/NWGawmg

@brandyscarney 
I just tried, but I think I misunderstood. We still cannot make the toggle 100% width. Because the "handle" doesn't slide till the end of the toggle.

As you can see in the screenshot below. And as per the original question. The handle doesn't adapt to the new width of the toggle. I only goes as far as the default toggle width.
![Screenshot from 2020-05-05 03-02-02](https://user-images.githubusercontent.com/21295129/81015818-f6725b80-8e7c-11ea-8b1f-275abafa5c25.png)

**Comment by mattsteve** [comment]
I made a simple reproduction on jsfiddle, seems to be working. Maybe there's some specific CSS you're adding to it that is causing an issue?

https://jsfiddle.net/k2gv980n/

![image](https://user-images.githubusercontent.com/34715493/81017058-986b5700-8e2f-11ea-9ffc-e9b1060f7e3b.png)

**Comment by vohrahul** [comment]
> @vohrahul
> I made a simple reproduction on jsfiddle, seems to be working. Maybe there's some specific CSS you're adding to it that is causing an issue?
> 
> https://jsfiddle.net/k2gv980n/
> 
> ![image](https://user-images.githubusercontent.com/34715493/81017058-986b5700-8e2f-11ea-9ffc-e9b1060f7e3b.png)

Damn! I rechecked and we are using ionic v4.10.3. Looks like need to migrate to 5.1. Dont know how I missed this last time. Well, thanks. I am sure it will work with v5.1

**Comment by mattsteve** [comment]
> 
> 
> @vohrahul `5.1.0` was released last week so you can try this out now. slightly_smiling_face
> 
> Here's a Codepen with different customizations: https://codepen.io/brandyscarney/pen/NWGawmg

Looks good, one bug I've found is in "md" mode you can't override the handle background when the toggle is checked. It always shows the primary theme color.

To reproduce in this demo, change
```
<ion-toggle mode="ios" class="all-custom"></ion-toggle>
```
To:
```
<ion-toggle mode="md" class="all-custom"></ion-toggle>
```

**Comment by vohrahul** [comment]
> > @vohrahul `5.1.0` was released last week so you can try this out now. slightly_smiling_face
> > Here's a Codepen with different customizations: https://codepen.io/brandyscarney/pen/NWGawmg
> 
> Looks good, one bug I've found is in "md" mode you can't override the handle background when the toggle is checked. It always shows the primary theme color.
> 
> To reproduce in this demo, change
> 
> ```
> <ion-toggle mode="ios" class="all-custom"></ion-toggle>
> ```
> 
> To:
> 
> ```
> <ion-toggle mode="md" class="all-custom"></ion-toggle>
> ```
> 
> Edit:
> At least in the way that you did it. Looks like there's a "handle-background-checked".

My problem is not related to "md" mode.
I am actually trying to have a "swipe right to unluck" feature (similar to old ios lock screens). The design has to look same for both android and ios. Hence I used `mode="ios"`

But this is still not solved for me, as we are using ionic v4. And the changes require the app to be on ionic v5.1 minimum.

Anyway, I can achieve this function of full width ios mode toggle in ionic v4 ?

**Comment by mattiaskjellsson** [comment]
I'm using ionic ionic 5.4.16. The code pen seems to do what 

> @vohrahul `5.1.0` was released last week so you can try this out now. 🙂
> 
> Here's a Codepen with different customizations: https://codepen.io/brandyscarney/pen/NWGawmg

The code pen seems nice and all, but using ionic 5.4.16 the --handle-width seems to not really render correctly?
