### ISSUE TITLE
bug: ng add @ionic/angular@next throws error when add to Angular project (Angular 9 Ivy + Ionic RC4), have PR

### ISSUE THREAD

**Issue by hiepxanh** [ionic-team/ionic#20435]
# Bug Report
### Ionic version:
[x] 5 RC4

### With @next

`ng add @ionic/angular@next --project=mobile` throws the following error:

```
E:\my-workspace>ng add @ionic/angular@next --project=mobile
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Could not find file for path: projects/mobile/projects/mobile/src/app/app.module.ts
```
### With normal
`ng add @ionic/angular --project=mobile` throws the following error:

```
E:\my-workspace>ng add @ionic/angular --project=mobile
Installing packages for tooling via npm.
Installed packages for tooling via npm.
The package that you are trying to add does not support schematics. You can try using a different version of the package or contact the package author to add ng-add support.
```

## Steps to reproduce:
```
ng new my-workspace --createApplication="false"
cd my-workspace
ng generate application mobile
ng add @ionic/angular --project=mobile
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am unable to reproduce the behavior you are describing. These are the steps I am following:

1. Run `ng new`
2. Name the project "testProject"
3. Add Angular Routing.
4. Use CSS instead of a preprocessor.
5. `cd testProject`
6. `ng add @ionic/angular@next --project=testProject`.

Are these the correct steps to reproduce?

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20436 and will be available in an upcoming release of Ionic Framework.

**Comment by hiepxanh** [comment]
thank you so much sir, have a good day sir

**Comment by mohamedsharaf** [comment]
@liamdebeasi 

ionic serve livereload has problem i think related to this as cordova.js not injected with flag --liverelaod

but if you build or run without it its injected

not sure should i make issue here or command line is right
https://github.com/ionic-team/ionic-cli/issues/4313

**Comment by liamdebeasi** [comment]
@mohamedsharaf I replied to your issue. Ionic 4 does not support Angular 9, please try with Ionic 5.

**Comment by mohamedsharaf** [comment]
i can confirm its still exist same problem here is a public repo so u can test
https://github.com/mohamedsharaf/i5ng9
run 
ionic cordova run ios -l
