### ISSUE TITLE
When keyboard open in latest IOS, input field behind the keyboard if form is long

### ISSUE THREAD

**Issue by herobarua** [ionic-team/ionic#21288]
Ionic:

   Ionic CLI                     : 6.8.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.0
   @angular-devkit/build-angular : 0.901.5
   @angular-devkit/schematics    : 9.1.5
   @angular/cli                  : 9.1.5
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 4 other plugins)

Utility:

   cordova-res (update available: 0.14.0) : 0.6.0
   native-run (update available: 1.0.0)   : 0.2.8

System:

   ios-deploy : 1.9.2
   ios-sim    : 8.0.2
   NodeJS     : v10.15.0 (/usr/local/bin/node)
   npm        : 6.14.5
   OS         : macOS Catalina
   Xcode      : Xcode 11.4.1 Build version 11E503a

Here is my ionic info where i am using ionic 5 with latest ionic cordova keyboard plugin. 

Below issue preview
<img width="752" alt="Screenshot at May 13 16-25-35" src="https://user-images.githubusercontent.com/1532317/81801530-66947780-9536-11ea-9473-8e3bb435e8cc.png">

**Comment by mobileias** [comment]
Hello Ionic team we are also using latest ionic angular and we see same issue 

here is screenshot

![image_2020_05_13T10_45_31_059Z](https://user-images.githubusercontent.com/14582437/81803355-326c8700-9535-11ea-9a0c-5c2813ea1bce.png)

is there any fix for this issue ?

Thanks in advance

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has already been resolved via https://github.com/ionic-team/ionic/pull/21206, and a fix will be available in an upcoming release of Ionic Framework.

**Comment by herobarua** [comment]
@liamdebeasi when new version available?

Regards

**Comment by liamdebeasi** [comment]
We plan on having the new release out soon.

**Comment by mobileias** [comment]
@liamdebeasi 
thank a lot Sir.

**Comment by joeszewski** [comment]
I'm using Ionic Angular 5.1.1, running as a PWA, and this is still not working correctly for me.  Here's an example of what the structure of my template looks like:

```
<form>
 <ion-item lines="none" color="dark">
  <ion-label position="stacked">First Name</ion-label>
  <ion-input type="text"></ion-input>
 </ion-item>

 <ion-item lines="none" color="dark">
  <ion-label position="stacked">Last Name</ion-label>
  <ion-input type="text"></ion-input>
 </ion-item>

 <ion-item lines="none" color="dark">
  <ion-label position="stacked">Email</ion-label>
  <ion-input type="email"></ion-input>
 </ion-item>

 <ion-item lines="none" color="dark">
  <ion-label position="stacked">Password</ion-label>
  <ion-input type="password"></ion-input>
 </ion-item>

 <ion-button shape="round" expand="full">Create Account</ion-button>
</form>
```

Would it make a difference to wrap the ion-items in an ion-list?

My PROD version of the app is running Ionic Angular 5.0.5, and the scroll assist works beautifully when tapping through the list of inputs.
_______________________

Ionic Info:
Ionic:

   Ionic CLI                     : 5.2.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.900.7
   @angular-devkit/schematics    : 9.0.7
   @angular/cli                  : 9.0.7
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 1.5.1
   @capacitor/core : 1.1.1

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.3 (/usr/local/Cellar/node/9.6.1/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave

**Comment by liamdebeasi** [comment]
@joeszewski Please open a new issue with a code reproduction we can use to reproduce the issue. Thanks!
