### ISSUE TITLE
ionic 2 menu grey square

### ISSUE THREAD

**Issue by vonovak** [ionic-team/ionic#6416]
#### Short description of the problem:

When using the project created by `ionic start mem2 tutorial --v2` and running on android 5.1.1 device.

When the app starts up:
![screenshot_2016-05-03-17-53-14](https://cloud.githubusercontent.com/assets/1566403/14989785/ba4772c0-1159-11e6-8c35-25ccc33dbdbc.png)

When I toggle the menu and then hide it. (note the grey square under the hamburger menu)
![screenshot_2016-05-03-17-51-03](https://cloud.githubusercontent.com/assets/1566403/14989784/ba3d453e-1159-11e6-9661-e28127f70d42.png)
#### What behavior are you expecting?

I would expect the images to look the same (note the grey square under the hamburger menu).

**Steps to reproduce:**
1. `ionic start mem2 tutorial --v2`
2. `ionic run android`
3. Swipe the menu right and left / toggle it by the "toggle menu" button or hamburger menu button and swipe back. Apparently the bug doesn't exhibit itself each time you run the app.

**When the grey square is present, it seems that pressing the blue button makes it go away.**

```
Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS: Distributor ID: Ubuntu Description: Ubuntu 15.10 
Node Version: v5.10.1
```

**Comment by jgw96** [comment]
Ahh good catch! I can see this with our `sidemenu` starter on Android 5.1.1, Android 6.0.1 and Android N dev preview 2.

**Comment by MartineNavara** [comment]
I'm experiencing the same problem with Ionic 1 (version Delhi and higher).

**Comment by WHarris22** [comment]
+1 in Ionic 2 beta 7

**Comment by nyankobu010** [comment]
+1 occurs in platform:ios too when using chrome debugger

**Comment by nyankobu010** [comment]
Found out this only occurs when the content doesn't overflow the particular screen size being tested (when you aren't able to scroll for a particular view). Hope this helps someone with finding the root cause.

**Comment by jgw96** [comment]
Hello all , this has been fixed for our beta.10 release. If you would like to try it out early you can install the latest ionic 2 nightly with `sudo npm install ionic-angular@nightly`. There are some very minor breaking changes in this release that we will have full upgrade instructions for when we release but the biggest thing is that 
```
<ion-navbar *navbar>
</ion-navbar>
```
should be changed to this
```
<ion-header>
  <ion-navbar>
  </ion-navbar>
</ion-header>
```

Thanks for using Ionic!

**Comment by jgw96** [comment]
Seeing this issue again with the latest nightly. Reopening to investigate more.

**Comment by lordgreg** [comment]
Exactly the same issue.

**Comment by jgw96** [comment]
Note for the team: Did some debugging on this and got some really weird results. If you inspect the page with chrome dev tools that little grey square does not seem to be in the dom.

**Comment by ghenry22** [comment]
I still see the little gray square on both ios and android devices with beta10

**Comment by tarasok** [comment]
It is also reproduced on ionic 1.3. 
I found steps:
1) Open app
2) Open active (the same) page through slide menu
Result: 
Small grey box in empty list. When I'm trying to change any style of content (in chrome dev tools) - the box is gone, even I revert my changes.... it's really strange...

**Comment by WHarris22** [comment]
I've noticed two things when I play around in the chrome dev tools, but neither really help with finding the cause of it but could help with the DOM location (`ion-header` or `scroll-content` or my testing could just be wrong all together!).

First off, if you untick the `ion-header` element property `position: absolute;` the header goes back to `position: static;` which hides the header behind the `ion-content` as this element is 100% height and width. So this must mean it is something to do with the `ion-header` element right?

And second, I've also noticed that if you increase the property `margin-top:56px;` to lets say 100px on the `scroll-content` element inside the `ion-content` this causes the square to move further down the screen.

So two different thiings seem to affect the grey square but are not child or parent elements they are more sibling / adjacent to each other. Hmmmm

Note: changing values in chrome inspector cause the square to disappear, so you have to open and close the menu again to see where it gets re-positioned.

**Comment by WHarris22** [comment]
I think i've came to the conclusion that it is the scrollvar of the `scroll-content` element!! 

On the `scroll-content` element if you change `overflow-y: scroll;` to `overflow-y:auto;` it gets rid of it. And also if you change `overflow-x: hidden;` to `oveflow-x:scroll;` the grey square changes slightly due to the vertical and horizontal scrollbars overlapping. :)

**Comment by WHarris22** [comment]
Something else that seems to make the square disappear is when you do the following

`<ion-content fullscreen="true">`

I hope this information is helpful for implementing a fix

**Comment by kodeine** [comment]
i started to see this more often in beta11 than beta8

**Comment by jgw96** [comment]
Hello! Happy to report that i can no longer reproduce this issue with the latest nightly. Because of this, I am going to be closing this issue for now. Thanks for using Ionic!

**Comment by laserus** [comment]
@jgw96 please reopen, the bug is there again.

**Comment by FilipSuk** [comment]
@jgw96 The issue occured for me in modal page (.modal-wrapper). I fixed it with overflow-y:auto on .scroll-content.

Version: 2.0.0-rc.1-201610191717 (nigtly)

**Comment by kodeine** [comment]
@jgw96 i'm getting the square box in rc1 as well.

**Comment by ghenry22** [comment]
Also getting this in rc1

**Comment by jbw91** [comment]
@jgw96 also happening to me in rc1.

**Comment by ibonkonesa** [comment]
In my case, that only happen if I have inputs and these don't have placeholder...

**Comment by felipeands** [comment]
ion-content fullscreen="true" 
still fixing it on rc1

**Comment by laserus** [comment]
@felipeands it is not a fix, probably the grey box is there behind navbar.... =)

**Comment by gregvis** [comment]
This is also happening to me on ionic 1.3.2. Can a fix be implemented for ionic v1 as well? 

I tried the suggestion to set 
`.scroll-content{
    overflow-y: auto;
}`
Which seems to fix it when your main content is displayed, however, when I open the left side menu, it appears again, but disappears when the menu is closed. 
![image](https://cloud.githubusercontent.com/assets/8760745/20143348/b2ffb4a8-a666-11e6-9b7f-2476af187ef1.png)

**Comment by aggarwalankush** [comment]
same issue in rc2 also

**Comment by peterpeterparker** [comment]
@WHarris22 is right, with fullscreen="true" the menu grey square doesn't appear

**Comment by royipressburger** [comment]
Alos seeing this with rc3 when focus on input

**Comment by aluknot** [comment]
Same here with rc3, the only workarounds for me was:

1) set `overflow`, `overflow-y` or `overflow-x` (depends on the situation) to `auto`

2) 
```
::-webkit-scrollbar,
*::-webkit-scrollbar {
      display: none;
}
```

**Comment by jgw96** [comment]
Hello all! Are you guys still seeing this in RC4 ?

**Comment by ghenry22** [comment]
Yep it's back in RC4

**Comment by sryze** [comment]
I'm seeing this with 1.3.2 too (in a side menu). The `scroll-content` fix worked for me 👍

**Comment by shamank** [comment]
I'm facing this in 2.1.0 (fresh install). `<ion-content fullscreen="true">` is a valid workaround in the meanwhile btw... Any real fix regarding this issue would be very much appreciated. Thanks

**Comment by laser-me** [comment]
OK, I had a moment to look at this. The box that we see is a "scrollbar" for a page where it is not needed. Happens only by toggling menu. All examples with this gray box, has a content of elements that do not require overflow. 

So I switched off in the ionic class `".scroll-content"` rule `"overflow-y: scroll"`.

This fixed the issue and for content that really needs "scrollbar" on the right everything works fine. Just let you know.

**Comment by chandanch** [comment]
It does not happen for the right side menu

**Comment by peterpeterparker** [comment]
For the record, Ionic 2.3.0, our grey square friend is still displayed.
To avoid it I continue to use the fullScreen attribute of the content.

**Comment by AlvaroHerrero** [comment]
In ionic 1.3.3 I have removed the grey square setting "overflow: auto;" (in css) to the ion-content tag.

**Comment by s3ppo** [comment]
in 3.0.1 i still can see it

**Comment by chandanch** [comment]
It occurs for the left side-menu

**Comment by TanayParikh** [comment]
Facing the same issue with ionic 3.

**Comment by jd0048** [comment]
i am facing same issue for grey square friend in ionic 2 please check attach screenshot it 
`ion-content{
overflow: auto;
}

::-webkit-scrollbar, *::-webkit-scrollbar {
display: none;
}`
this solutions work but it will hide scroll bar to throughout project so thats why its not help full for me


![scrollbar-3](https://user-images.githubusercontent.com/28923124/27039026-5162f38e-4faa-11e7-9c8b-458fb3c720c9.png)

Please fix asap for grey square friend!!!

**Comment by Langstra** [comment]
@jgw96 Unfortunately I am also experiencing this one. I updated the framework to the latest version. 
At first it is not there. However, after opening and closing the menu once it is there. I see this on Android 7.1.2.
Also here is ionic info.
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.0 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.1.2 browser 4.1.0
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v7.3.0
    OS         : Linux 4.10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 4.6.1

**Comment by chandanch** [comment]
Its occurring for the left side menu

**Comment by cgaeking** [comment]
As soon as I tap on the main content screen it appears. Using ioinic framework 3.4.2 as well.

**Comment by h1ghland3r** [comment]
Bug is still here in Ionic 3.4.0..

**Comment by trebor678** [comment]
+1

**Comment by shamank** [comment]
Still happening un 3.4.2 :(

**Comment by nrcrabbe** [comment]
Happening for me in 3.4.1 for both the left _and right_ side menu. Only when the content doesn't require a scroll.

It is definitely a part of `div.scroll-content` as you can set `top: 20px !important` and watch it move down next time.

I set a long async list and it appeared while the list was unpopulated and then disappeared as soon as the async call returned and the list was populated.

**Comment by tintucraju** [comment]
Happening for me too in 3.4.1 for left side menu.  

For the time being i have tried the following and fixed.

scroll-content{
      overflow-y: auto !important;
}

**Comment by neguso** [comment]
It's happening also in 3.5.0

**Comment by rubenheymans** [comment]
@WHarris22 I think its .scroll-content

**Comment by gardziej** [comment]
Still in 3.12.0 :(

**Comment by vksgautam1** [comment]
it is still

**Comment by muhlenbrock** [comment]
Esto me funciono
<ion-content padding fullscreen="true">

**Comment by chandanch** [comment]
I tried this: 
````html
<ion-menu class="full-width">...</ion-menu>
````
````css
.full-width {
    width: 50%;
    display: flex
}
````

**Comment by gregor-srdic** [comment]
I am also noticing this in many of my ionic apps, even with the newest 3.7.1 version. Has anyone been able to solve it yet?

**Comment by rapideinternet** [comment]
Still there...

**Comment by ptitjes** [comment]
@brandyscarney Is there something preventing the resolution of this issue ?

From what I've read in https://github.com/ionic-team/ionic/pull/10431 and https://github.com/ionic-team/ionic/issues/6022#issuecomment-228110736, the `overflow-y: scroll` on `scroll-content` is only there to make ios users happy with momentum scrolling.

As said in https://github.com/ionic-team/ionic/issues/6022#issuecomment-279400592, this can be fixed in the following way:
```
.content .scroll-content {
    overflow-y: auto;
}
.content-ios .scroll-content {
    overflow-y: scroll;
}
```

Could we have that in 3.7.2 ? It is a bit annoying to have to have fixes like these in our stylesheets ?

**Comment by ricricucit** [comment]
I found this bug as well, in a totally unrelated project (not an ionic project)...and it's somehow appearing only when I'm using **hammerjs**. Can somebody confirm this?

**Comment by bhumin3i** [comment]
still same issue please any one help me on this.

> ionic info 

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.2
    npm  : 5.5.1
    OS   : Windows 7

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy

**Comment by patwaswapnil** [comment]
Same issue 3.9.2

**Comment by marcusaaronb** [comment]
![image](https://user-images.githubusercontent.com/16932359/39100792-164f6114-46c2-11e8-8ff8-919b18b28799.png)
 how to remove squire object once click my button. thank you

**Comment by jbw91** [comment]
@marcusaaronb That's the `outline` CSS property. Browsers have a default styling added. There's a lot of reasons to keep the outline, for example mentioned here: [Stop Messing with the Browser's Default Focus outline](https://www.tjvantoll.com/2013/01/28/stop-messing-with-the-browsers-default-focus-outline/)

In terms of a native app, if you don't plan on having it accessible on the web but just from app stores, then you can get rid of it using the following: 

```
:focus {
    outline: none;
}
```

**Comment by vksgautam1** [comment]
In ionic 4 aplha 2 also have same  found this issue since ionic 2

**Comment by Hanzofm** [comment]
This problem still happening on ionic 3.9.2

`
ionic info

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 6.4.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    ios-sim           : 6.1.2 
    Node              : v9.9.0
    npm               : 5.7.1 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.3.1 Build version 9E501 

Environment Variables:

    ANDROID_HOME : /Users/user/Library/Android/sdk

Misc:

    backend : pro

`



Workaround proposed by @patwaswapnil works like a charm

> .scroll-content{
    overflow-y:auto !important;
}
