### ISSUE TITLE
ionic2 ion-segment ion-segment-button not works with ngFor properly.

### ISSUE THREAD

**Issue by lygstate** [ionic-team/ionic#6923]
#### Short description of the problem:

When using ion-segment, ion-segment-button with ngFor,
Once the length of dataArray are increased, the 
ion-segment-button corresponded increased entries of dataArray 
can not be clicked.

```
<ion-segment [(ngModel)]="valve.selectDay">
  <ion-segment-button *ngFor="let info of dataArray" value="{{info.day}}">{{info.day+1}}天</ion-segment-button>
</ion-segment>
```
#### What behavior are you expecting?

Once push entries into the end of dataArray
,the newly ion-segment-button can be click with selection properly.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by lygstate** [comment]
@jgw96 Here is the demo,
http://plnkr.co/edit/Or0Ik1S1HtvUVq3YYdhC

Once you change the period days from `3 days` to `4 days`.
Click the `4TH DAY` would have no effect.

**Comment by mnasyrov** [comment]
As a workaround I manually trigger rebinding logic of Segment component after updating my view state:

```
@Component()
export class MyComponent {
    @ViewChild(Segment)
    private segment: Segment;

    private ngOnInit() {
        this.fetchData().then(data => {
            // Data processing...
            
            // Hotfix for dynamic ion-segment-buttons issue
            setTimeout(() => {
                if (this.segment) {
                    this.segment.ngAfterViewInit();
                }
            });
        });
    }
}
```

**Comment by lygstate** [comment]
@mnasyrov Can you modify your hot fix works with the fork of 
http://plnkr.co/edit/Or0Ik1S1HtvUVq3YYdhC

**Comment by mnasyrov** [comment]
@lygstate it's a rather trivial, I just copy-pasted the workaround above. http://plnkr.co/edit/GyCLkQ0aFgFpPr9QUSiO

**Comment by bjoernbur** [comment]
👍

**Comment by anatoly-spb** [comment]
Is it hard to fix it?

**Comment by badpenguin** [comment]
still open? :-( i've just noticed this bug also both ngModel is not changed and ioncChange event is not fired ; it works if i use static HTML instead of an *ngFor loop

**Comment by pablozandona** [comment]
+1

**Comment by decpio** [comment]
+1

**Comment by Ross-Rawlins** [comment]
+1

**Comment by eduardoyutaka** [comment]
I ran into the same problem and solved it by adding a click event like this:

<ion-segment [(ngModel)]="valve.selectDay">
  <ion-segment-button *ngFor="let info of dataArray" value="{{info.day}}" (click)="setInfo(info.day)">{{selectedDay+1}}天</ion-segment-button>
</ion-segment>

and then you can define the setInfo() function and a selectedDay variable at the component as something like:

selectedDay;
if (dataArray[0].info.day != nil) {
  selectedDay = dataArray[0].info.day;
}
...
setInfo(day) {
   selectedDay = day+1;
}

I am not really sure how your code is since the demo is different than the original problem, but the logic behind is adding a click event in order to change the segmented button content so that it matches the button's value.

**Comment by blckshrk** [comment]
Hi everyone,

I found a more simplest workaround for this bug. You can add a `ngIf`on the `ion-segment` like the following : 
```html
<ion-segment *ngIf="businessCollection" [(ngModel)]="businessId">
    <ion-segment-button *ngFor="let business of businessCollection" value="{{ business.id }}">{{ business.title }}</ion-segment-button>
</ion-segment>
```
As the DOM is rebuilded only when the `businessCollection` array is filled (in the subscribe), it seem to fix the issue.

**Comment by mebibou** [comment]
@blckshrk this gives me an exception:
```
Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'
```

**Comment by blckshrk** [comment]
@mebibou Can't help you without the code ;-)

**Comment by decpio** [comment]
The main problem with ion-segment and *ngFor disappear about 6 weeks ago with ionic actualization. Latest version also works well. Can you close the issue?

**Comment by blckshrk** [comment]
I confirm what @decpio says. No bug in the `3.2.1` version.

**Comment by mnasyrov** [comment]
Still have the issue with dynamically rebuilding `ion-segment-button` items in Ionic v3.2.1.

**Comment by mebibou** [comment]
@mnasyrov thanks for this, `this.segment._inputUpdated();` will also update the selected tab, was missing this one

**Comment by qiluo** [comment]
Ran into similar problem. In my case, I have to dynamically create segment buttons after fetching some date from backend, so basically my code looks like 
```
ionViewDidLoad() {
  this.service.get().subscribe(
    res => { this.segmentArray = res; this.selectedSegment = segmentArray[0]; }
  );
```

```
<ion-segment [(ngModel)]="selectedSegment">
      <ion-segment-button *ngFor="let index of segmentArray" value="{{segmentArray[index]}}">
        segmentArray[index]
      </ion-segment-button>
</ion-segment>
```

Then I cannot properly select segment button which didn't show correct appearance
None of above workaround fix my issue

I'm on
```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : ios 4.4.0
    Ionic Framework                 : ionic-angular 3.4.0

System:

    Node       : v6.11.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
    npm        : 3.10.10
```

**Comment by helmerdavila** [comment]
My temp solution

```html
<ion-segment *ngIf="generatedArray">
      <ion-segment-button *ngFor="let item of generatedArray" value="{{segmentArray[index]}}" (tap)="contendChanged(generatedArray.someValue1)">
           generatedArray.someValue2
      </ion-segment-button>
</ion-segment>
`

(tap) work and you can send data to a function.

**Comment by zds-jack** [comment]
in  ionic V3.6   Segment class has no more function ngAfterViewInit()。 Use ngAfterContentInit() instead.

**Comment by manojbhardwaj** [comment]
value="{{generatedArray.someValue1]}} how it will we work check your someValue1]}}

**Comment by mccumb01** [comment]
If you use an *ngFor or *ngIf structural directive to generate your `<ion-segment-button>` elements, and you change either:
1) the number of buttons in the segment or
2) their values ...
The result is that it *appears* as if you cannot select updated segment buttons ... 

But you can - it all works fine *except* for applying the `segment-activated` CSS class to the selected button and removing it from all the others. The options, data model, and DOM all update fine, which is why none of my messing w/`ngOnChanges` or ChangeDetectionRef `.detectChanges()` had any impact - everything was already up to date except for the CSS! 

The `segment-activated` class gets stuck on whichever element existed in the previous list, if any. 
If your updated segment data source has identical values & number of buttons, no problem. 
But, if all the segment values change, the `segment-activated` class won't appear for any of them.

After waaay too long screwing around with this, I finally hacked together this ugly approach to fix the problem, and it'll do since I've wasted so much time on it ... 
```
<ion-segment formArrayName="segmentArray">
	<ion-segment-button *ngFor="let option of options; let i=index;" [value]="i" (tap)="setOption(i, $event)">{{option}}</ion-segment-button>
</ion-segment>

public setOption(index, event) {
    if (this.options[index] != null) {
      this.selectedSegment = this.options[index]; 

      //note you have to use "tap" or "click" - if you bind to "ionSelected" you don't get the "target" property
      let segments = event.target.parentNode.children;
      let len = segments.length;
      for (let i=0; i < len; i++) {
        segments[i].classList.remove('segment-activated');
      }
      event.target.classList.add('segment-activated');
}
```
It's ugly & ol'skool, but it gets the job done and I have no more time to make it fancy ...  

Would be nice if somebody could take a look at how the CSS classes get applied after changes to the `<ion-segment>` component and fix this.  

Thanks ~

**Comment by RaphaelBadia** [comment]
@mccumb01 thank you so much

**Comment by patrickmcd** [comment]
I had to do a more RxJS-friendly version which I based on @mccumb01's excellent comment. Rather than `event.target` to get the segment, I use `ViewChild`. Below is the general idea. Who's looking forward to a new Stencil segment?

```TypeScript
<ion-segment #mySegment>
  <ion-segment-button
  *ngFor="let segment of segments$ | async; let i = index; trackBy:trackByFn;"
  (click)="selectedCpmIntSubject.next(i)">
    {{segment.title}}
  </ion-segment-button>
</ion-segment>
```

```TypeScript
@ViewChild('mySegment') mySegment: ElementRef;

//...

selectedSegmentSubject = new BehaviorSubject(null);

selectedSegment$ = this.selectedSegmentSubject
.distinctUntilChanged()
.do(selectedSegment => {
  // do stuff
});

//...

setSegment(selectedIndex) {

  const segments: any[] = Array.from(
    this.mySegment.nativeElement.children
  );

  segments.forEach( (segment, segmentIndex) => {
    if (segmentIndex === selectedIndex) {
      segment.classList.add('segment-activated');
    } else {
      segment.classList.remove('segment-activated');
    }
  });

}

//...

trackByFn = (idx, obj): string => obj.$key;

```

**Comment by ntziolis** [comment]
Still not fixed? We run into this issue in every project and it seems very sillier and sillier to employ the above workarounds again and again.

**Comment by xinbenlv** [comment]
+1

**Comment by manojbhardwaj** [comment]
Please Try with   [id]="mcq.ques_id"  value="{{mcq.ques_id}}"  and  (ionSelect)
<ion-segment-button  *ngFor="let mcq of mcqdata; let i=index;"  [id]="mcq.ques_id"  value="{{mcq.ques_id}}" (ionSelect)="selectsegment(mcq,i)"  [ngClass]="{'active': selectedIdx == i}">
                  <strong>Queastion{{i+1}}</strong>
              </ion-segment-button>

**Comment by saty932** [comment]
@mccumb01  
Thanks for your solution.The only issue i am facing right now is i am unable to make first ionic segment button active.After click it's working properly.

How can i make first segment button active when page loads first time.

Mycode:
```
 <ion-toolbar color="tabbarcolor" *ngIf="tabBarStatus">
    <ion-segment [(ngModel)]="selectedcategory"  >
      <ion-segment-button (click)="setOption(i, $event)" [value]="i" *ngFor=" let category of displayingCategories; let i=index; " [style.width]="category.width" [style.opacity]="getOpacity(category.status)">
        {{category.category}}
      </ion-segment-button>
    </ion-segment>
  </ion-toolbar>
 ```

**Comment by ddoerr** [comment]
+1

**Comment by ac3ju** [comment]
2018 and still exists :/

**Comment by kennethross** [comment]
+1

**Comment by brandyscarney** [comment]
Thanks for the issue and sorry for the lack of response! This issue has recently been fixed in Ionic for the v4 release. I just tested it on our `core` branch and I can se it working now:

<img src="http://g.recordit.co/Cow3mfsSbj.gif">

I'll try to come back and update this issue when we have something for you all to test out. 

Related commits:
https://github.com/ionic-team/ionic/commit/242960dc29e9efdc180108925a45680cb3191a7a
https://github.com/ionic-team/ionic/commit/1e6e481958fea99e5c29628d0339cccde1305302

**Comment by rbaumi** [comment]
And when do you plan to release v4 with this fix?

**Comment by xyboox** [comment]
Could one apply the fix before v4 release? If so, how?

**Comment by aleixpellicer** [comment]
Ran into the same problem.

Weird that such issue still exists after 2 years... let's hope it's fixed soon!

**Comment by brandyscarney** [comment]
This has been fixed as part of Ionic v4. I will update the issue when we have a version out that is ready to be tested. Locking for now.

**Comment by brandyscarney** [comment]
Version 4 beta has been released, for more information please see this blog post: https://blog.ionicframework.com/announcing-ionic-4-beta/

Closing this issue as resolved with v4, thank you!
