### ISSUE TITLE
RC4(ios): Side menu takes multiple taps to close

### ISSUE THREAD

**Issue by ghenry22** [ionic-team/ionic#9716]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

1) start a new side menu project
2) on the ios emulator or device tap the hamburger to open the side menu (all good)
3) tap the hamburger to close the side menu (takes 2-3 taps before it responds).

**Expected behavior:**
Side menu closes with a single tap of the hamburger icon.

This was an issue in previous versions, was fixed and working fine in RC3.  Has now come back in RC4.

**Steps to reproduce:**
1) start a new side menu project
2) on the ios emulator or device tap the hamburger to open the side menu (all good)
3) tap the hamburger to close the side menu (takes 2-3 taps before it responds).

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a

```

**Comment by jgw96** [comment]
Thanks for posting an issue, we will look into this.

**Comment by ghenry22** [comment]
I know it was a long running issue before that was fixed, seems to have crept back in again

**Comment by rtmruczek** [comment]
I'm still experiencing this issue in `2.0.1`.

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: OS X El Capitan
Node Version: v7.2.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by crissi** [comment]
m2

**Comment by shawnlan** [comment]
Tested on iPad (iOS 10) with Ionic 2.0.1. Looks like if you try to close the menu too soon after it opens, it doesn't close. Wait for a few seconds then one tap should be able to close it.

And there seems a 300ms delay when closing the menu. Please check.

**Comment by shawnlan** [comment]
Anyone? I think it is important for a quality app. I can still see this issue with Ionic 2.2.0.

**Comment by ghenry22** [comment]
This is specific to UIWebview on iOS device.  with wkwebview, android or browser there is no issue.

**Comment by shawnlan** [comment]
Are we recommended to use wkwebview?

**Comment by ghenry22** [comment]
this is STILL an issue with UIWebview, wkwebview and android do not have this issue.  Not being able to close the side menu is pretty big issue with basic essential functionality for an app.

"use wkwebview" is really not a suitable answer until the wkwebview reaches feature parity with uiwebview in terms of background processing, access to file system, cors issues, keyboard focus issue, self signed certificate support and a bunch of other things that you lose by going to wkwebview at the moment.

Could someone please look at this?

**Comment by rtmruczek** [comment]
Still an issue for me as well in 3.x. It's really unfortunate that this issue keeps cropping up.

**Comment by dev-manager-uk** [comment]
Hello @jgw96 - we have this bug too.  Is there an eta do you know?  
Thanks :)
